#!/usr/bin/env python3
import os
BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"
def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f: f.write('\n'.join(lines) + '\n')

# 53. Maximum Subarray
write(f"{BASE}/15_greedy/0053_maximum_subarray.py", ['"""LeetCode 53: Maximum Subarray - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: Kadane\'s O(n)','class Solution_v1:','    def maxSubArray(self, nums: List[int]) -> int:','        cur=mx=nums[0]','        for n in nums[1:]: cur=max(n,cur+n); mx=max(mx,cur)','        return mx','# Variation 2: Divide and conquer O(n log n)','class Solution_v2:','    def maxSubArray(self, nums: List[int]) -> int:','        def dc(l,r):','            if l==r: return nums[l]','            m=(l+r)//2','            left_max=right_max=0; cur=0','            for i in range(m,l-1,-1): cur+=nums[i]; left_max=max(left_max,cur)','            cur=0','            for i in range(m+1,r+1): cur+=nums[i]; right_max=max(right_max,cur)','            return max(dc(l,m),dc(m+1,r),left_max+right_max)','        return dc(0,len(nums)-1)','if __name__ == "__main__":','    nums=[-2,1,-3,4,-1,2,1,-5,4]','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r=Cls().maxSubArray(nums[:])','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: max={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/15_greedy/0053_maximum_subarray.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<int> n={-2,1,-3,4,-1,2,1,-5,4};','    auto t=chrono::high_resolution_clock::now();','    int cur=n[0],mx=n[0];','    for(int i=1;i<(int)n.size();i++){cur=max(n[i],cur+n[i]);mx=max(mx,cur);}','    cout<<"var1: "<<mx<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 55. Jump Game
write(f"{BASE}/15_greedy/0055_jump_game.py", ['"""LeetCode 55: Jump Game - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: Greedy max reach','class Solution_v1:','    def canJump(self, nums: List[int]) -> bool:','        reach=0','        for i,n in enumerate(nums):','            if i>reach: return False','            reach=max(reach,i+n)','        return True','# Variation 2: DP from right','class Solution_v2:','    def canJump(self, nums: List[int]) -> bool:','        goal=len(nums)-1','        for i in range(len(nums)-2,-1,-1):','            if i+nums[i]>=goal: goal=i','        return goal==0','if __name__ == "__main__":','    nums=[2,3,1,1,4]','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r=Cls().canJump(nums[:])','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: can={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/15_greedy/0055_jump_game.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<int> n={2,3,1,1,4};','    auto t=chrono::high_resolution_clock::now();','    int reach=0;','    for(int i=0;i<(int)n.size();i++){if(i>reach){cout<<"var1: false"<<endl;return 0;}reach=max(reach,i+n[i]);}','    cout<<"var1: true"<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 45. Jump Game II
write(f"{BASE}/15_greedy/0045_jump_game_ii.py", ['"""LeetCode 45: Jump Game II - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: Greedy (BFS levels)','class Solution_v1:','    def jump(self, nums: List[int]) -> int:','        jumps=cur_end=far=0','        for i in range(len(nums)-1):','            far=max(far,i+nums[i])','            if i==cur_end: jumps+=1; cur_end=far','        return jumps','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1],1):','        tracemalloc.start(); t0=time.perf_counter()','        r=Cls().jump([2,3,1,1,4])','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: jumps={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/15_greedy/0045_jump_game_ii.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<int> n={2,3,1,1,4};','    auto t=chrono::high_resolution_clock::now();','    int jumps=0,cur=0,far=0;','    for(int i=0;i<(int)n.size()-1;i++){far=max(far,i+n[i]);if(i==cur){jumps++;cur=far;}}','    cout<<"var1: "<<jumps<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 134. Gas Station
write(f"{BASE}/15_greedy/0134_gas_station.py", ['"""LeetCode 134: Gas Station - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: One-pass greedy','class Solution_v1:','    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:','        total=tank=start=0','        for i in range(len(gas)):','            diff=gas[i]-cost[i]; total+=diff; tank+=diff','            if tank<0: start=i+1; tank=0','        return start if total>=0 else -1','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().canCompleteCircuit([1,2,3,4,5],[3,4,5,1,2])','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: start={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/15_greedy/0134_gas_station.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<int> gas={1,2,3,4,5},cost={3,4,5,1,2};','    auto t=chrono::high_resolution_clock::now();','    int total=0,tank=0,start=0;','    for(int i=0;i<(int)gas.size();i++){int d=gas[i]-cost[i];total+=d;tank+=d;if(tank<0){start=i+1;tank=0;}}','    cout<<"var1: "<<(total>=0?start:-1)<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 846 / 763. Partition Labels
write(f"{BASE}/15_greedy/0763_partition_labels.py", ['"""LeetCode 763: Partition Labels - Medium"""','import time, tracemalloc','# Variation 1: Last occurrence greedy','class Solution_v1:','    def partitionLabels(self, s: str):','        last={c:i for i,c in enumerate(s)}','        start=end=0; res=[]','        for i,c in enumerate(s):','            end=max(end,last[c])','            if i==end: res.append(end-start+1); start=i+1','        return res','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().partitionLabels("ababcbacadefegdehijhklij")','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/15_greedy/0763_partition_labels.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    string s="ababcbacadefegdehijhklij";','    auto t=chrono::high_resolution_clock::now();','    int last[26]={}; for(int i=0;i<(int)s.size();i++) last[s[i]-\'a\']=i;','    int start=0,end=0; vector<int> res;','    for(int i=0;i<(int)s.size();i++){end=max(end,last[s[i]-\'a\']);if(i==end){res.push_back(end-start+1);start=i+1;}}','    for(int x:res) cout<<x<<" "; cout<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 678. Valid Parenthesis String
write(f"{BASE}/15_greedy/0678_valid_parenthesis_string.py", ['"""LeetCode 678: Valid Parenthesis String - Medium"""','import time, tracemalloc','# Variation 1: Greedy count low/high','class Solution_v1:','    def checkValidString(self, s: str) -> bool:','        lo=hi=0','        for c in s:','            if c=="(": lo+=1; hi+=1','            elif c==")": lo-=1; hi-=1','            else: lo-=1; hi+=1','            if hi<0: return False','            lo=max(lo,0)','        return lo==0','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().checkValidString("(*)")','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/15_greedy/0678_valid_parenthesis_string.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    string s="(*)";','    auto t=chrono::high_resolution_clock::now();','    int lo=0,hi=0;','    for(char c:s){if(c==\'(\'){lo++;hi++;}else if(c==\')\'){lo--;hi--;}else{lo--;hi++;}if(hi<0){cout<<"var1: false"<<endl;return 0;}lo=max(lo,0);}','    cout<<"var1: "<<(lo==0)<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

print("Section 15 Greedy done!")
