#!/usr/bin/env python3
import os
BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"
def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f: f.write('\n'.join(lines) + '\n')

# 48. Rotate Image
write(f"{BASE}/17_math_and_geometry/0048_rotate_image.py", ['"""LeetCode 48: Rotate Image - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: Reverse then transpose (or transpose then reverse)','class Solution_v1:','    def rotate(self, matrix: List[List[int]]) -> None:','        matrix.reverse()','        for i in range(len(matrix)):','            for j in range(i):','                matrix[i][j],matrix[j][i] = matrix[j][i],matrix[i][j]','# Variation 2: Rotate by rings (4 cells at a time)','class Solution_v2:','    def rotate(self, matrix: List[List[int]]) -> None:','        n = len(matrix)','        for i in range(n // 2):','            for j in range(i, n - i - 1):','                tmp = matrix[i][j]','                matrix[i][j] = matrix[n - 1 - j][i]','                matrix[n - 1 - j][i] = matrix[n - 1 - i][n - 1 - j]','                matrix[n - 1 - i][n - 1 - j] = matrix[j][n - 1 - i]','                matrix[j][n - 1 - i] = tmp','if __name__ == "__main__":','    import copy','    matrix = [[1,2,3],[4,5,6],[7,8,9]]','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        m = copy.deepcopy(matrix)','        tracemalloc.start(); t0=time.perf_counter()','        Cls().rotate(m)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/0048_rotate_image.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<vector<int>> matrix = {{1,2,3},{4,5,6},{7,8,9}};','    auto t=chrono::high_resolution_clock::now();','    reverse(matrix.begin(), matrix.end());','    for(int i=0; i<matrix.size(); i++){','        for(int j=0; j<i; j++){','            swap(matrix[i][j], matrix[j][i]);','        }','    }','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 54. Spiral Matrix
write(f"{BASE}/17_math_and_geometry/0054_spiral_matrix.py", ['"""LeetCode 54: Spiral Matrix - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: Boundaries simulation','class Solution_v1:','    def spiralOrder(self, matrix: List[List[int]]) -> List[int]:','        res = []','        left, right = 0, len(matrix[0])','        top, bottom = 0, len(matrix)','        while left < right and top < bottom:','            for i in range(left, right): res.append(matrix[top][i])','            top += 1','            for i in range(top, bottom): res.append(matrix[i][right - 1])','            right -= 1','            if not (left < right and top < bottom): break','            for i in range(right - 1, left - 1, -1): res.append(matrix[bottom - 1][i])','            bottom -= 1','            for i in range(bottom - 1, top - 1, -1): res.append(matrix[i][left])','            left += 1','        return res','if __name__ == "__main__":','    matrix = [[1,2,3],[4,5,6],[7,8,9]]','    tracemalloc.start(); t0=time.perf_counter()','    r = Solution_v1().spiralOrder(matrix)','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/0054_spiral_matrix.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<vector<int>> matrix = {{1,2,3},{4,5,6},{7,8,9}};','    auto t=chrono::high_resolution_clock::now();','    vector<int> res;','    int left = 0, right = matrix[0].size();','    int top = 0, bottom = matrix.size();','    while (left < right && top < bottom) {','        for (int i = left; i < right; i++) res.push_back(matrix[top][i]);','        top++;','        for (int i = top; i < bottom; i++) res.push_back(matrix[i][right - 1]);','        right--;','        if (!(left < right && top < bottom)) break;','        for (int i = right - 1; i >= left; i--) res.push_back(matrix[bottom - 1][i]);','        bottom--;','        for (int i = bottom - 1; i >= top; i--) res.push_back(matrix[i][left]);','        left++;','    }','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 73. Set Matrix Zeroes
write(f"{BASE}/17_math_and_geometry/0073_set_matrix_zeroes.py", ['"""LeetCode 73: Set Matrix Zeroes - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: O(1) space with first row and col as markers','class Solution_v1:','    def setZeroes(self, matrix: List[List[int]]) -> None:','        ROWS, COLS = len(matrix), len(matrix[0])','        rowZero = False','        for r in range(ROWS):','            for c in range(COLS):','                if matrix[r][c] == 0:','                    matrix[0][c] = 0','                    if r > 0: matrix[r][0] = 0','                    else: rowZero = True','        for r in range(1, ROWS):','            for c in range(1, COLS):','                if matrix[0][c] == 0 or matrix[r][0] == 0:','                    matrix[r][c] = 0','        if matrix[0][0] == 0:','            for r in range(ROWS): matrix[r][0] = 0','        if rowZero:','            for c in range(COLS): matrix[0][c] = 0','# Variation 2: O(m+n) space','class Solution_v2:','    def setZeroes(self, matrix: List[List[int]]) -> None:','        r_zero = set(); c_zero = set()','        for r in range(len(matrix)):','            for c in range(len(matrix[0])):','                if matrix[r][c] == 0:','                    r_zero.add(r); c_zero.add(c)','        for r in range(len(matrix)):','            for c in range(len(matrix[0])):','                if r in r_zero or c in c_zero:','                    matrix[r][c] = 0','if __name__ == "__main__":','    import copy','    matrix = [[1,1,1],[1,0,1],[1,1,1]]','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        m = copy.deepcopy(matrix)','        tracemalloc.start(); t0=time.perf_counter()','        Cls().setZeroes(m)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/0073_set_matrix_zeroes.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<vector<int>> matrix = {{1,1,1},{1,0,1},{1,1,1}};','    auto t=chrono::high_resolution_clock::now();','    int ROWS = matrix.size(), COLS = matrix[0].size();','    bool rowZero = false;','    for(int r=0; r<ROWS; r++){','        for(int c=0; c<COLS; c++){','            if(matrix[r][c] == 0){','                matrix[0][c] = 0;','                if(r > 0) matrix[r][0] = 0;','                else rowZero = true;','            }','        }','    }','    for(int r=1; r<ROWS; r++){','        for(int c=1; c<COLS; c++){','            if(matrix[0][c] == 0 || matrix[r][0] == 0) matrix[r][c] = 0;','        }','    }','    if(matrix[0][0] == 0) for(int r=0; r<ROWS; r++) matrix[r][0] = 0;','    if(rowZero) for(int c=0; c<COLS; c++) matrix[0][c] = 0;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 202. Happy Number
write(f"{BASE}/17_math_and_geometry/0202_happy_number.py", ['"""LeetCode 202: Happy Number - Easy"""','import time, tracemalloc','# Variation 1: Hash set cycle detection','class Solution_v1:','    def isHappy(self, n: int) -> bool:','        visit = set()','        while n not in visit:','            visit.add(n)','            n = self.sumOfSquares(n)','            if n == 1: return True','        return False','    def sumOfSquares(self, n: int) -> int:','        output = 0','        while n:','            digit = n % 10','            digit = digit ** 2','            output += digit','            n = n // 10','        return output','# Variation 2: Fast and slow pointers (Floyd\'s)','class Solution_v2:','    def isHappy(self, n: int) -> bool:','        slow, fast = n, self.sumOfSquares(n)','        while fast != 1 and slow != fast:','            slow = self.sumOfSquares(slow)','            fast = self.sumOfSquares(self.sumOfSquares(fast))','        return fast == 1','    def sumOfSquares(self, n: int) -> int:','        output = 0','        while n:','            digit = n % 10','            digit = digit ** 2','            output += digit','            n = n // 10','        return output','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().isHappy(19)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/0202_happy_number.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int sumOfSquares(int n) {','    int output = 0;','    while (n) { int digit = n % 10; digit = digit * digit; output += digit; n = n / 10; }','    return output;','}','int main(){','    int n = 19;','    auto t=chrono::high_resolution_clock::now();','    int slow = n, fast = sumOfSquares(n);','    while(fast != 1 && slow != fast){ slow = sumOfSquares(slow); fast = sumOfSquares(sumOfSquares(fast)); }','    cout<<"var1: "<<(fast == 1)<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 66. Plus One
write(f"{BASE}/17_math_and_geometry/0066_plus_one.py", ['"""LeetCode 66: Plus One - Easy"""','import time, tracemalloc','from typing import List','# Variation 1: Reverse array carry logic','class Solution_v1:','    def plusOne(self, digits: List[int]) -> List[int]:','        digits = digits[::-1]','        one, i = 1, 0','        while one:','            if i < len(digits):','                if digits[i] == 9: digits[i] = 0','                else: digits[i] += 1; one = 0','            else:','                digits.append(1); one = 0','            i += 1','        return digits[::-1]','# Variation 2: Backwards traversal','class Solution_v2:','    def plusOne(self, digits: List[int]) -> List[int]:','        for i in range(len(digits)-1, -1, -1):','            if digits[i] == 9: digits[i] = 0','            else: digits[i] += 1; return digits','        return [1] + digits','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().plusOne([1,2,3])','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/0066_plus_one.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<int> digits = {1,2,3};','    auto t=chrono::high_resolution_clock::now();','    for(int i = digits.size() - 1; i >= 0; i--) {','        if(digits[i] == 9) digits[i] = 0;','        else { digits[i] += 1; break; }','    }','    if(digits[0] == 0) { digits.insert(digits.begin(), 1); }','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 50. Pow(x, n)
write(f"{BASE}/17_math_and_geometry/0050_pow_x_n.py", ['"""LeetCode 50: Pow(x, n) - Medium"""','import time, tracemalloc','# Variation 1: Fast exponentiation Recursive','class Solution_v1:','    def myPow(self, x: float, n: int) -> float:','        def helper(x, n):','            if x == 0: return 0','            if n == 0: return 1','            res = helper(x * x, n // 2)','            return x * res if n % 2 else res','        res = helper(x, abs(n))','        return res if n >= 0 else 1 / res','# Variation 2: Fast exponentiation Iterative','class Solution_v2:','    def myPow(self, x: float, n: int) -> float:','        if n < 0: x = 1 / x; n = -n','        res = 1','        while n:','            if n % 2: res *= x','            x *= x; n //= 2','        return res','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().myPow(2.0, 10)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/0050_pow_x_n.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    double x = 2.0; long long n = 10;','    auto t=chrono::high_resolution_clock::now();','    if(n < 0){ x = 1 / x; n = -n; }','    double res = 1;','    while(n){ if(n % 2) res *= x; x *= x; n /= 2; }','    cout<<"var1: "<<res<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 43. Multiply Strings
write(f"{BASE}/17_math_and_geometry/0043_multiply_strings.py", ['"""LeetCode 43: Multiply Strings - Medium"""','import time, tracemalloc','# Variation 1: Digits array simulation','class Solution_v1:','    def multiply(self, num1: str, num2: str) -> str:','        if "0" in [num1, num2]: return "0"','        res = [0] * (len(num1) + len(num2))','        num1, num2 = num1[::-1], num2[::-1]','        for i1 in range(len(num1)):','            for i2 in range(len(num2)):','                digit = int(num1[i1]) * int(num2[i2])','                res[i1 + i2] += digit','                res[i1 + i2 + 1] += res[i1 + i2] // 10','                res[i1 + i2] = res[i1 + i2] % 10','        res, beg = res[::-1], 0','        while beg < len(res) and res[beg] == 0: beg += 1','        return "".join(map(str, res[beg:]))','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().multiply("123", "456")','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/0043_multiply_strings.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    string num1 = "123", num2 = "456";','    auto t=chrono::high_resolution_clock::now();','    if(num1 == "0" || num2 == "0") { cout<<"var1: 0"<<endl; return 0; }','    vector<int> res(num1.size() + num2.size(), 0);','    reverse(num1.begin(), num1.end()); reverse(num2.begin(), num2.end());','    for(int i=0; i<num1.size(); i++){','        for(int j=0; j<num2.size(); j++){','            int digit = (num1[i] - \'0\') * (num2[j] - \'0\');','            res[i + j] += digit;','            res[i + j + 1] += res[i + j] / 10;','            res[i + j] %= 10;','        }','    }','    reverse(res.begin(), res.end());','    int beg = 0; while(beg < res.size() && res[beg] == 0) beg++;','    string ans = ""; for(; beg < res.size(); beg++) ans += to_string(res[beg]);','    cout<<"var1: "<<ans<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 2013. Detect Squares
write(f"{BASE}/17_math_and_geometry/2013_detect_squares.py", ['"""LeetCode 2013: Detect Squares - Medium"""','import time, tracemalloc','from collections import defaultdict','from typing import List','# Variation 1: Hash map of points','class DetectSquares_v1:','    def __init__(self):','        self.ptsCount = defaultdict(int)','        self.pts = []','    def add(self, point: List[int]) -> None:','        self.ptsCount[tuple(point)] += 1','        self.pts.append(point)','    def count(self, point: List[int]) -> int:','        res = 0; px, py = point','        for x, y in self.pts:','            if (abs(py - y) != abs(px - x)) or x == px or y == py: continue','            res += self.ptsCount[(x, py)] * self.ptsCount[(px, y)]','        return res','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    obj = DetectSquares_v1()','    obj.add([3,10]); obj.add([11,2]); obj.add([3,2])','    r = obj.count([11,10])','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/17_math_and_geometry/2013_detect_squares.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    auto t=chrono::high_resolution_clock::now();','    unordered_map<int, unordered_map<int, int>> ptsCount; vector<pair<int, int>> pts;','    auto add = [&](int x, int y){ ptsCount[x][y]++; pts.push_back({x, y}); };','    auto count = [&](int px, int py){ int res = 0; for(auto& p : pts){ int x = p.first, y = p.second; if(abs(py - y) != abs(px - x) || x == px || y == py) continue; res += ptsCount[x][py] * ptsCount[px][y]; } return res; };','    add(3,10); add(11,2); add(3,2); int res = count(11,10);','    cout<<"var1: "<<res<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])


print("Section 17 done!")
