#!/usr/bin/env python3
"""Generator for Section 12: Advanced Graphs"""
import os
BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"
def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f: f.write('\n'.join(lines) + '\n')

# 332. Reconstruct Itinerary
write(f"{BASE}/12_advanced_graphs/0332_reconstruct_itinerary.py", [
'"""LeetCode 332: Reconstruct Itinerary - Hard"""',
'import time, tracemalloc',
'from collections import defaultdict',
'',
'# Variation 1: Hierholzer DFS (Eulerian path)',
'class Solution_v1:',
'    def findItinerary(self, tickets):',
'        graph = defaultdict(list)',
'        for src,dst in sorted(tickets, reverse=True): graph[src].append(dst)',
'        route = []',
'        def dfs(airport):',
'            while graph[airport]: dfs(graph[airport].pop())',
'            route.append(airport)',
'        dfs("JFK")',
'        return route[::-1]',
'',
'# Variation 2: Iterative Hierholzer',
'class Solution_v2:',
'    def findItinerary(self, tickets):',
'        graph = defaultdict(list)',
'        for src,dst in sorted(tickets, reverse=True): graph[src].append(dst)',
'        stack, route = ["JFK"], []',
'        while stack:',
'            while graph[stack[-1]]: stack.append(graph[stack[-1]].pop())',
'            route.append(stack.pop())',
'        return route[::-1]',
'',
'if __name__ == "__main__":',
'    tickets=[["MUC","LHR"],["JFK","MUC"],["SFO","SJC"],["LHR","SFO"]]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().findItinerary(tickets)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/12_advanced_graphs/0332_reconstruct_itinerary.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 332: Reconstruct Itinerary - Hard */',
'map<string,vector<string>> g12;',
'vector<string> route12;',
'void dfs12(const string& a){ while(!g12[a].empty()){ string nb=g12[a].back(); g12[a].pop_back(); dfs12(nb); } route12.push_back(a); }',
'int main(){',
'    vector<pair<string,string>> tickets={{"MUC","LHR"},{"JFK","MUC"},{"SFO","SJC"},{"LHR","SFO"}};',
'    for(auto&[s,d]:tickets) g12[s].push_back(d);',
'    for(auto&[k,v]:g12) sort(v.rbegin(),v.rend());',
'    auto s=chrono::high_resolution_clock::now();',
'    dfs12("JFK"); reverse(route12.begin(),route12.end());',
'    cout<<"var1: "; for(auto& x:route12) cout<<x<<" "; cout<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 1584. Min Cost to Connect All Points (Prim's & Kruskal's)
write(f"{BASE}/12_advanced_graphs/1584_min_cost_to_connect_all_points.py", [
'"""LeetCode 1584: Min Cost to Connect All Points - Medium"""',
'import time, tracemalloc',
'import heapq',
'from typing import List',
'',
"# Variation 1: Prim's algorithm O(n^2 log n)",
'class Solution_v1:',
'    def minCostConnectPoints(self, points: List[List[int]]) -> int:',
'        n=len(points); visited=set(); total=0',
'        heap=[(0,0)]  # (cost, node)',
'        while len(visited)<n:',
'            cost,u=heapq.heappop(heap)',
'            if u in visited: continue',
'            visited.add(u); total+=cost',
'            for v in range(n):',
'                if v not in visited:',
'                    d=abs(points[u][0]-points[v][0])+abs(points[u][1]-points[v][1])',
'                    heapq.heappush(heap,(d,v))',
'        return total',
'',
"# Variation 2: Kruskal's with Union Find",
'class Solution_v2:',
'    def minCostConnectPoints(self, points: List[List[int]]) -> int:',
'        n=len(points)',
'        edges=[]',
'        for i in range(n):',
'            for j in range(i+1,n):',
'                d=abs(points[i][0]-points[j][0])+abs(points[i][1]-points[j][1])',
'                edges.append((d,i,j))',
'        edges.sort(); parent=list(range(n)); total=0; used=0',
'        def find(x):',
'            while parent[x]!=x: parent[x]=parent[parent[x]]; x=parent[x]',
'            return x',
'        for d,u,v in edges:',
'            pu,pv=find(u),find(v)',
'            if pu==pv: continue',
'            parent[pv]=pu; total+=d; used+=1',
'            if used==n-1: break',
'        return total',
'',
'if __name__ == "__main__":',
'    pts=[[0,0],[2,2],[3,10],[5,2],[7,0]]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().minCostConnectPoints(pts)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: cost={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/12_advanced_graphs/1584_min_cost_to_connect_all_points.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 1584: Min Cost to Connect All Points - Medium */',
'int main(){',
'    vector<pair<int,int>> pts={{0,0},{2,2},{3,10},{5,2},{7,0}};',
'    int n=pts.size();',
'    // Prim',
'    auto s=chrono::high_resolution_clock::now();',
'    vector<bool> vis(n,false); priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> pq; pq.push({0,0});',
'    long long total=0; int cnt=0;',
'    while(cnt<n){',
'        auto[cost,u]=pq.top(); pq.pop();',
'        if(vis[u]) continue; vis[u]=true; total+=cost; cnt++;',
'        for(int v=0;v<n;v++) if(!vis[v]){ int d=abs(pts[u].first-pts[v].first)+abs(pts[u].second-pts[v].second); pq.push({d,v}); }',
'    }',
'    cout<<"var1 (Prim): "<<total<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 743. Network Delay Time (Dijkstra)
write(f"{BASE}/12_advanced_graphs/0743_network_delay_time.py", [
'"""LeetCode 743: Network Delay Time - Medium"""',
'import time, tracemalloc',
'import heapq',
'from collections import defaultdict',
'from typing import List',
'',
'# Variation 1: Dijkstra with min-heap',
'class Solution_v1:',
'    def networkDelayTime(self, times: List[List[int]], n: int, k: int) -> int:',
'        graph=defaultdict(list)',
'        for u,v,w in times: graph[u].append((v,w))',
'        dist={i:float("inf") for i in range(1,n+1)}; dist[k]=0',
'        heap=[(0,k)]',
'        while heap:',
'            d,u=heapq.heappop(heap)',
'            if d>dist[u]: continue',
'            for v,w in graph[u]:',
'                if dist[u]+w<dist[v]: dist[v]=dist[u]+w; heapq.heappush(heap,(dist[v],v))',
'        mx=max(dist.values())',
'        return mx if mx<float("inf") else -1',
'',
'# Variation 2: Bellman-Ford O(VE)',
'class Solution_v2:',
'    def networkDelayTime(self, times: List[List[int]], n: int, k: int) -> int:',
'        dist=[float("inf")]*(n+1); dist[k]=0',
'        for _ in range(n-1):',
'            for u,v,w in times:',
'                if dist[u]+w<dist[v]: dist[v]=dist[u]+w',
'        mx=max(dist[1:])',
'        return mx if mx<float("inf") else -1',
'',
'if __name__ == "__main__":',
'    times=[[2,1,1],[2,3,1],[3,4,1]]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().networkDelayTime(times,4,2)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: delay={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/12_advanced_graphs/0743_network_delay_time.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 743: Network Delay Time - Medium */',
'int main(){',
'    int n=4,k=2;',
'    vector<tuple<int,int,int>> times={{2,1,1},{2,3,1},{3,4,1}};',
'    vector<vector<pair<int,int>>> g(n+1);',
'    for(auto[u,v,w]:times) g[u].push_back({v,w});',
'    auto s=chrono::high_resolution_clock::now();',
'    vector<int> dist(n+1,INT_MAX); dist[k]=0;',
'    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> pq; pq.push({0,k});',
'    while(!pq.empty()){ auto[d,u]=pq.top();pq.pop(); if(d>dist[u]) continue; for(auto[v,w]:g[u]) if(dist[u]+w<dist[v]){dist[v]=dist[u]+w;pq.push({dist[v],v});} }',
'    int mx=*max_element(dist.begin()+1,dist.end());',
'    cout<<"var1: "<<(mx==INT_MAX?-1:mx)<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 778. Swim in Rising Water
write(f"{BASE}/12_advanced_graphs/0778_swim_in_rising_water.py", [
'"""LeetCode 778: Swim in Rising Water - Hard"""',
'import time, tracemalloc',
'import heapq',
'from typing import List',
'',
'# Variation 1: Dijkstra (min-heap on max elevation path)',
'class Solution_v1:',
'    def swimInWater(self, grid: List[List[int]]) -> int:',
'        n=len(grid); visited=set()',
'        heap=[(grid[0][0],0,0)]',
'        while heap:',
'            t,r,c=heapq.heappop(heap)',
'            if (r,c) in visited: continue',
'            visited.add((r,c))',
'            if r==n-1 and c==n-1: return t',
'            for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
'                nr,nc=r+dr,c+dc',
'                if 0<=nr<n and 0<=nc<n and (nr,nc) not in visited:',
'                    heapq.heappush(heap,(max(t,grid[nr][nc]),nr,nc))',
'        return -1',
'',
'# Variation 2: Binary search + BFS',
'class Solution_v2:',
'    def swimInWater(self, grid: List[List[int]]) -> int:',
'        from collections import deque',
'        n=len(grid)',
'        def canReach(t):',
'            if grid[0][0]>t: return False',
'            q=deque([(0,0)]); vis={( 0,0)}',
'            while q:',
'                r,c=q.popleft()',
'                if r==n-1 and c==n-1: return True',
'                for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
'                    nr,nc=r+dr,c+dc',
'                    if 0<=nr<n and 0<=nc<n and (nr,nc) not in vis and grid[nr][nc]<=t:',
'                        vis.add((nr,nc)); q.append((nr,nc))',
'            return False',
'        lo,hi=0,n*n-1',
'        while lo<hi:',
'            mid=(lo+hi)//2',
'            if canReach(mid): hi=mid',
'            else: lo=mid+1',
'        return lo',
'',
'if __name__ == "__main__":',
'    grid=[[0,2],[1,3]]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().swimInWater(grid)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: time={r}, mem={mem}bytes, time_us={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/12_advanced_graphs/0778_swim_in_rising_water.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 778: Swim in Rising Water - Hard */',
'int main(){',
'    vector<vector<int>> grid={{0,2},{1,3}}; int n=grid.size();',
'    priority_queue<tuple<int,int,int>,vector<tuple<int,int,int>>,greater<>> pq;',
'    pq.push({grid[0][0],0,0}); vector<vector<bool>> vis(n,vector<bool>(n,false));',
'    auto s=chrono::high_resolution_clock::now();',
'    int ans=0;',
'    while(!pq.empty()){ auto[t,r,c]=pq.top();pq.pop(); if(vis[r][c]) continue; vis[r][c]=true; ans=max(ans,t); if(r==n-1&&c==n-1){cout<<"var1: "<<ans<<endl;break;} int dr[]={1,-1,0,0},dc[]={0,0,1,-1}; for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d]; if(nr>=0&&nr<n&&nc>=0&&nc<n&&!vis[nr][nc]) pq.push({max(t,grid[nr][nc]),nr,nc});} }',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 787. Cheapest Flights Within K Stops
write(f"{BASE}/12_advanced_graphs/0787_cheapest_flights_within_k_stops.py", [
'"""LeetCode 787: Cheapest Flights Within K Stops - Medium"""',
'import time, tracemalloc',
'import heapq',
'from typing import List',
'',
'# Variation 1: Bellman-Ford (k+1 relaxations)',
'class Solution_v1:',
'    def findCheapestPrice(self, n, flights, src, dst, k) -> int:',
'        prices=[float("inf")]*n; prices[src]=0',
'        for _ in range(k+1):',
'            tmp=prices[:]',
'            for u,v,w in flights:',
'                if prices[u]+w<tmp[v]: tmp[v]=prices[u]+w',
'            prices=tmp',
'        return prices[dst] if prices[dst]!=float("inf") else -1',
'',
'# Variation 2: Modified Dijkstra (stops as state)',
'class Solution_v2:',
'    def findCheapestPrice(self, n, flights, src, dst, k) -> int:',
'        from collections import defaultdict',
'        graph=defaultdict(list)',
'        for u,v,w in flights: graph[u].append((v,w))',
'        heap=[(0,src,0)]  # cost, node, stops',
'        visited={}',
'        while heap:',
'            cost,u,stops=heapq.heappop(heap)',
'            if u==dst: return cost',
'            if stops>k: continue',
'            if u in visited and visited[u]<=stops: continue',
'            visited[u]=stops',
'            for v,w in graph[u]: heapq.heappush(heap,(cost+w,v,stops+1))',
'        return -1',
'',
'if __name__ == "__main__":',
'    flights=[[0,1,100],[1,2,100],[0,2,500]]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().findCheapestPrice(3,flights,0,2,1)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: price={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/12_advanced_graphs/0787_cheapest_flights_within_k_stops.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 787: Cheapest Flights Within K Stops - Medium */',
'int main(){',
'    int n=3,src=0,dst=2,k=1;',
'    vector<tuple<int,int,int>> flights={{0,1,100},{1,2,100},{0,2,500}};',
'    auto s=chrono::high_resolution_clock::now();',
'    vector<int> prices(n,INT_MAX); prices[src]=0;',
'    for(int i=0;i<=k;i++){ vector<int> tmp=prices; for(auto[u,v,w]:flights) if(prices[u]!=INT_MAX&&prices[u]+w<tmp[v]) tmp[v]=prices[u]+w; prices=tmp; }',
'    cout<<"var1: "<<(prices[dst]==INT_MAX?-1:prices[dst])<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

print("Section 12 advanced graphs done!")
