#!/usr/bin/env python3
import os
BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"
def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f: f.write('\n'.join(lines) + '\n')

# 57. Insert Interval
write(f"{BASE}/16_intervals/0057_insert_interval.py", ['"""LeetCode 57: Insert Interval - Medium"""','import time, tracemalloc','from typing import List','class Solution_v1:','    def insert(self, intervals: List[List[int]], newInterval: List[int]) -> List[List[int]]:','        res=[]; i=0; n=len(intervals)','        while i<n and intervals[i][1]<newInterval[0]: res.append(intervals[i]); i+=1','        while i<n and intervals[i][0]<=newInterval[1]: newInterval[0]=min(newInterval[0],intervals[i][0]); newInterval[1]=max(newInterval[1],intervals[i][1]); i+=1','        res.append(newInterval)','        return res+intervals[i:]','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().insert([[1,3],[6,9]],[2,5])','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/16_intervals/0057_insert_interval.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<pair<int,int>> iv={{1,3},{6,9}},res; pair<int,int> nw={2,5};','    auto t=chrono::high_resolution_clock::now();','    int i=0,n=iv.size();','    while(i<n&&iv[i].second<nw.first) res.push_back(iv[i++]);','    while(i<n&&iv[i].first<=nw.second){nw.first=min(nw.first,iv[i].first);nw.second=max(nw.second,iv[i].second);i++;}','    res.push_back(nw);','    while(i<n) res.push_back(iv[i++]);','    for(auto&p:res) cout<<"["<<p.first<<","<<p.second<<"] "; cout<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 56. Merge Intervals
write(f"{BASE}/16_intervals/0056_merge_intervals.py", ['"""LeetCode 56: Merge Intervals - Medium"""','import time, tracemalloc','from typing import List','# Variation 1: Sort and merge','class Solution_v1:','    def merge(self, intervals: List[List[int]]) -> List[List[int]]:','        intervals.sort(); res=[intervals[0]]','        for s,e in intervals[1:]:','            if s<=res[-1][1]: res[-1][1]=max(res[-1][1],e)','            else: res.append([s,e])','        return res','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().merge([[1,3],[2,6],[8,10],[15,18]])','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/16_intervals/0056_merge_intervals.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<pair<int,int>> iv={{1,3},{2,6},{8,10},{15,18}};','    auto t=chrono::high_resolution_clock::now();','    sort(iv.begin(),iv.end());','    vector<pair<int,int>> res={iv[0]};','    for(auto&[s,e]:iv){if(s<=res.back().second)res.back().second=max(res.back().second,e);else res.push_back({s,e});}','    for(auto&p:res)cout<<"["<<p.first<<","<<p.second<<"] ";cout<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 435. Non-overlapping Intervals
write(f"{BASE}/16_intervals/0435_non_overlapping_intervals.py", ['"""LeetCode 435: Non-overlapping Intervals - Medium"""','import time, tracemalloc','from typing import List','class Solution_v1:','    def eraseOverlapIntervals(self, intervals: List[List[int]]) -> int:','        intervals.sort(key=lambda x:x[1]); count=0; end=float("-inf")','        for s,e in intervals:','            if s>=end: end=e','            else: count+=1','        return count','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().eraseOverlapIntervals([[1,2],[2,3],[3,4],[1,3]])','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: erase={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/16_intervals/0435_non_overlapping_intervals.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<pair<int,int>> iv={{1,2},{2,3},{3,4},{1,3}};','    auto t=chrono::high_resolution_clock::now();','    sort(iv.begin(),iv.end(),[](auto&a,auto&b){return a.second<b.second;});','    int cnt=0,end=INT_MIN;','    for(auto&[s,e]:iv){if(s>=end)end=e;else cnt++;}','    cout<<"var1: "<<cnt<<endl;','    auto e2=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e2-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 252/253. Meeting Rooms / Meeting Rooms II
write(f"{BASE}/16_intervals/0252_meeting_rooms.py", ['"""LeetCode 252: Meeting Rooms - Easy"""','import time, tracemalloc','from typing import List','class Solution_v1:','    def canAttendMeetings(self, intervals: List[List[int]]) -> bool:','        intervals.sort()','        for i in range(1,len(intervals)):','            if intervals[i][0]<intervals[i-1][1]: return False','        return True','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().canAttendMeetings([[0,30],[5,10],[15,20]])','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/16_intervals/0252_meeting_rooms.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<pair<int,int>> iv={{0,30},{5,10},{15,20}};','    auto t=chrono::high_resolution_clock::now();','    sort(iv.begin(),iv.end());','    bool ok=true;','    for(int i=1;i<(int)iv.size();i++) if(iv[i].first<iv[i-1].second){ok=false;break;}','    cout<<"var1: "<<ok<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

write(f"{BASE}/16_intervals/0253_meeting_rooms_ii.py", ['"""LeetCode 253: Meeting Rooms II - Medium"""','import time, tracemalloc','from typing import List','import heapq','# Variation 1: Min-heap','class Solution_v1:','    def minMeetingRooms(self, intervals: List[List[int]]) -> int:','        intervals.sort(); heap=[]','        for s,e in intervals:','            if heap and heap[0]<=s: heapq.heapreplace(heap,e)','            else: heapq.heappush(heap,e)','        return len(heap)','# Variation 2: Line sweep','class Solution_v2:','    def minMeetingRooms(self, intervals: List[List[int]]) -> int:','        events=[]','        for s,e in intervals: events+=[(s,1),(e,-1)]','        events.sort(); cur=mx=0','        for _,d in events: cur+=d; mx=max(mx,cur)','        return mx','if __name__ == "__main__":','    iv=[[0,30],[5,10],[15,20]]','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r=Cls().minMeetingRooms(iv[:])','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: rooms={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/16_intervals/0253_meeting_rooms_ii.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<pair<int,int>> iv={{0,30},{5,10},{15,20}};','    auto t=chrono::high_resolution_clock::now();','    sort(iv.begin(),iv.end()); priority_queue<int,vector<int>,greater<int>> h;','    for(auto&[s,e]:iv){if(!h.empty()&&h.top()<=s)h.pop();h.push(e);}','    cout<<"var1: "<<h.size()<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 1851. Minimum Interval to Include Each Query
write(f"{BASE}/16_intervals/1851_minimum_interval_to_include_each_query.py", ['"""LeetCode 1851: Minimum Interval to Include Each Query - Hard"""','import time, tracemalloc','from typing import List','import heapq','class Solution_v1:','    def minInterval(self, intervals: List[List[int]], queries: List[int]) -> List[int]:','        intervals.sort(); q_sorted=sorted(enumerate(queries),key=lambda x:x[1])','        res=[-1]*len(queries); heap=[]; i=0','        for idx,q in q_sorted:','            while i<len(intervals) and intervals[i][0]<=q:','                l,r=intervals[i]; heapq.heappush(heap,(r-l+1,r)); i+=1','            while heap and heap[0][1]<q: heapq.heappop(heap)','            if heap: res[idx]=heap[0][0]','        return res','if __name__ == "__main__":','    tracemalloc.start(); t0=time.perf_counter()','    r=Solution_v1().minInterval([[1,4],[2,4],[3,6],[4,4]],[2,3,4,5])','    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','    print(f"var1: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/16_intervals/1851_minimum_interval_to_include_each_query.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<pair<int,int>> iv={{1,4},{2,4},{3,6},{4,4}}; vector<int> q={2,3,4,5};','    auto t=chrono::high_resolution_clock::now();','    int n=q.size(); vector<int> res(n,-1);','    sort(iv.begin(),iv.end()); vector<int> idx(n); iota(idx.begin(),idx.end(),0); sort(idx.begin(),idx.end(),[&](int a,int b){return q[a]<q[b];});','    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> h; int i=0;','    for(int qi:idx){int qv=q[qi];while(i<(int)iv.size()&&iv[i].first<=qv){h.push({iv[i].second-iv[i].first+1,iv[i].second});i++;}while(!h.empty()&&h.top().second<qv)h.pop();if(!h.empty())res[qi]=h.top().first;}','    for(int x:res)cout<<x<<" ";cout<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

print("Section 16 Intervals done!")
