#!/usr/bin/env python3
"""
Batch generator for remaining NeetCode 150 sections 11-18.
Uses direct os.makedirs + open() to avoid string escaping issues.
"""
import os

BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"

def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

# =========================================================
# SECTION 11: GRAPHS (remaining 12 problems, 200 done above)
# =========================================================

# 133. Clone Graph
write(f"{BASE}/11_graphs/0133_clone_graph.py", [
    '"""LeetCode 133: Clone Graph - Medium"""',
    'import time, tracemalloc',
    'from collections import deque',
    '',
    'class Node:',
    '    def __init__(self, val=0, neighbors=None):',
    '        self.val = val',
    '        self.neighbors = neighbors if neighbors else []',
    '',
    '# Variation 1: DFS with hashmap',
    'class Solution_v1:',
    '    def cloneGraph(self, node):',
    '        if not node: return None',
    '        mp = {}',
    '        def dfs(n):',
    '            if n in mp: return mp[n]',
    '            clone = Node(n.val); mp[n] = clone',
    '            clone.neighbors = [dfs(nb) for nb in n.neighbors]',
    '            return clone',
    '        return dfs(node)',
    '',
    '# Variation 2: BFS with hashmap',
    'class Solution_v2:',
    '    def cloneGraph(self, node):',
    '        if not node: return None',
    '        mp = {node: Node(node.val)}; q = deque([node])',
    '        while q:',
    '            n = q.popleft()',
    '            for nb in n.neighbors:',
    '                if nb not in mp: mp[nb] = Node(nb.val); q.append(nb)',
    '                mp[n].neighbors.append(mp[nb])',
    '        return mp[node]',
    '',
    'if __name__ == "__main__":',
    '    n1=Node(1); n2=Node(2); n3=Node(3); n4=Node(4)',
    '    n1.neighbors=[n2,n4]; n2.neighbors=[n1,n3]; n3.neighbors=[n2,n4]; n4.neighbors=[n1,n3]',
    '    for Vi, Cls in enumerate([Solution_v1, Solution_v2], 1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        clone=Cls().cloneGraph(n1)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: clone.val={clone.val}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0133_clone_graph.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 133: Clone Graph - Medium */',
    'struct Node { int val; vector<Node*> neighbors; Node(int v):val(v){} };',
    '// var1: DFS with map',
    'unordered_map<Node*,Node*> mp;',
    'Node* dfs(Node* n){ if(!n) return nullptr; if(mp.count(n)) return mp[n]; mp[n]=new Node(n->val); for(auto nb:n->neighbors) mp[n]->neighbors.push_back(dfs(nb)); return mp[n]; }',
    'int main(){',
    '    Node *n1=new Node(1),*n2=new Node(2),*n3=new Node(3),*n4=new Node(4);',
    '    n1->neighbors={n2,n4}; n2->neighbors={n1,n3}; n3->neighbors={n2,n4}; n4->neighbors={n1,n3};',
    '    auto s=chrono::high_resolution_clock::now();',
    '    auto clone=dfs(n1); cout<<"var1: clone.val="<<clone->val<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 695. Max Area of Island
write(f"{BASE}/11_graphs/0695_max_area_of_island.py", [
    '"""LeetCode 695: Max Area of Island - Medium"""',
    'import time, tracemalloc',
    'from collections import deque',
    'from typing import List',
    'import copy',
    '',
    '# Variation 1: DFS recursive',
    'class Solution_v1:',
    '    def maxAreaOfIsland(self, grid: List[List[int]]) -> int:',
    '        rows, cols, mx = len(grid), len(grid[0]), 0',
    '        def dfs(r, c):',
    '            if r<0 or r>=rows or c<0 or c>=cols or grid[r][c]!=1: return 0',
    '            grid[r][c]=0',
    '            return 1+dfs(r+1,c)+dfs(r-1,c)+dfs(r,c+1)+dfs(r,c-1)',
    '        for r in range(rows):',
    '            for c in range(cols): mx=max(mx, dfs(r,c))',
    '        return mx',
    '',
    '# Variation 2: BFS',
    'class Solution_v2:',
    '    def maxAreaOfIsland(self, grid: List[List[int]]) -> int:',
    '        rows, cols, mx = len(grid), len(grid[0]), 0',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if grid[r][c]==1:',
    '                    area=0; q=deque([(r,c)]); grid[r][c]=0',
    '                    while q:',
    '                        cr,cc=q.popleft(); area+=1',
    '                        for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
    '                            nr,nc=cr+dr,cc+dc',
    '                            if 0<=nr<rows and 0<=nc<cols and grid[nr][nc]==1:',
    '                                grid[nr][nc]=0; q.append((nr,nc))',
    '                    mx=max(mx, area)',
    '        return mx',
    '',
    'if __name__ == "__main__":',
    '    grid_orig=[[0,0,1,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,1,1,0,1,0,0,0,0,0,0,0,0]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        g=copy.deepcopy(grid_orig)',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().maxAreaOfIsland(g)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: max_area={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0695_max_area_of_island.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 695: Max Area of Island - Medium */',
    'int dfs(vector<vector<int>>& g, int r, int c){ if(r<0||r>=(int)g.size()||c<0||c>=(int)g[0].size()||g[r][c]!=1) return 0; g[r][c]=0; return 1+dfs(g,r+1,c)+dfs(g,r-1,c)+dfs(g,r,c+1)+dfs(g,r,c-1); }',
    'int main(){',
    '    vector<vector<int>> g={{0,0,1,0,0,0,0,1,0,0,0,0,0},{0,0,0,0,0,0,0,1,1,1,0,0,0},{0,1,1,0,1,0,0,0,0,0,0,0,0}};',
    '    auto s=chrono::high_resolution_clock::now();',
    '    int mx=0; for(int r=0;r<(int)g.size();r++) for(int c=0;c<(int)g[0].size();c++) mx=max(mx,dfs(g,r,c));',
    '    cout<<"var1: max_area="<<mx<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 417. Pacific Atlantic Water Flow
write(f"{BASE}/11_graphs/0417_pacific_atlantic_water_flow.py", [
    '"""LeetCode 417: Pacific Atlantic Water Flow - Medium"""',
    'import time, tracemalloc',
    'from collections import deque',
    'from typing import List',
    '',
    '# Variation 1: DFS from ocean borders inward',
    'class Solution_v1:',
    '    def pacificAtlantic(self, heights: List[List[int]]) -> List[List[int]]:',
    '        rows, cols = len(heights), len(heights[0])',
    '        pac, atl = set(), set()',
    '        def dfs(r, c, visit, prev_h):',
    '            if r<0 or r>=rows or c<0 or c>=cols or (r,c) in visit or heights[r][c]<prev_h: return',
    '            visit.add((r,c))',
    '            for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]: dfs(r+dr,c+dc,visit,heights[r][c])',
    '        for c in range(cols): dfs(0,c,pac,heights[0][c]); dfs(rows-1,c,atl,heights[rows-1][c])',
    '        for r in range(rows): dfs(r,0,pac,heights[r][0]); dfs(r,cols-1,atl,heights[r][cols-1])',
    '        return [[r,c] for r,c in pac & atl]',
    '',
    '# Variation 2: BFS from ocean borders',
    'class Solution_v2:',
    '    def pacificAtlantic(self, heights: List[List[int]]) -> List[List[int]]:',
    '        rows, cols = len(heights), len(heights[0])',
    '        def bfs(starts):',
    '            visit = set(starts); q = deque(starts)',
    '            while q:',
    '                r,c = q.popleft()',
    '                for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
    '                    nr,nc = r+dr,c+dc',
    '                    if 0<=nr<rows and 0<=nc<cols and (nr,nc) not in visit and heights[nr][nc]>=heights[r][c]:',
    '                        visit.add((nr,nc)); q.append((nr,nc))',
    '            return visit',
    '        pac = bfs([(0,c) for c in range(cols)] + [(r,0) for r in range(rows)])',
    '        atl = bfs([(rows-1,c) for c in range(cols)] + [(r,cols-1) for r in range(rows)])',
    '        return [[r,c] for r,c in pac & atl]',
    '',
    'if __name__ == "__main__":',
    '    heights=[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().pacificAtlantic(heights)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: {len(r)} cells, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0417_pacific_atlantic_water_flow.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 417: Pacific Atlantic Water Flow - Medium */',
    'int R,C; vector<vector<int>>* H;',
    'void dfs(int r,int c,set<pair<int,int>>& vis,int ph){',
    '    if(r<0||r>=R||c<0||c>=C||vis.count({r,c})||(*H)[r][c]<ph) return;',
    '    vis.insert({r,c}); for(auto [dr,dc]:vector<pair<int,int>>{{1,0},{-1,0},{0,1},{0,-1}}) dfs(r+dr,c+dc,vis,(*H)[r][c]);',
    '}',
    'int main(){',
    '    vector<vector<int>> h={{1,2,2,3,5},{3,2,3,4,4},{2,4,5,3,1},{6,7,1,4,5},{5,1,1,2,4}};',
    '    H=&h; R=h.size(); C=h[0].size();',
    '    set<pair<int,int>> pac,atl;',
    '    auto s=chrono::high_resolution_clock::now();',
    '    for(int c=0;c<C;c++){dfs(0,c,pac,h[0][c]);dfs(R-1,c,atl,h[R-1][c]);}',
    '    for(int r=0;r<R;r++){dfs(r,0,pac,h[r][0]);dfs(r,C-1,atl,h[r][C-1]);}',
    '    int cnt=0; for(auto& p:pac) if(atl.count(p)) cnt++;',
    '    cout<<"var1: "<<cnt<<" cells"<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 994. Rotting Oranges
write(f"{BASE}/11_graphs/0994_rotting_oranges.py", [
    '"""LeetCode 994: Rotting Oranges - Medium"""',
    'import time, tracemalloc',
    'from collections import deque',
    'from typing import List',
    'import copy',
    '',
    '# Variation 1: Multi-source BFS',
    'class Solution_v1:',
    '    def orangesRotting(self, grid: List[List[int]]) -> int:',
    '        rows,cols=len(grid),len(grid[0]); q=deque(); fresh=0',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if grid[r][c]==2: q.append((r,c,0))',
    '                elif grid[r][c]==1: fresh+=1',
    '        time_val=0',
    '        while q:',
    '            r,c,t=q.popleft(); time_val=max(time_val,t)',
    '            for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
    '                nr,nc=r+dr,c+dc',
    '                if 0<=nr<rows and 0<=nc<cols and grid[nr][nc]==1:',
    '                    grid[nr][nc]=2; fresh-=1; q.append((nr,nc,t+1))',
    '        return time_val if fresh==0 else -1',
    '',
    '# Variation 2: Level-by-level BFS',
    'class Solution_v2:',
    '    def orangesRotting(self, grid: List[List[int]]) -> int:',
    '        rows,cols=len(grid),len(grid[0]); q=deque(); fresh=0',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if grid[r][c]==2: q.append((r,c))',
    '                elif grid[r][c]==1: fresh+=1',
    '        minutes=0',
    '        while q and fresh:',
    '            minutes+=1',
    '            for _ in range(len(q)):',
    '                r,c=q.popleft()',
    '                for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
    '                    nr,nc=r+dr,c+dc',
    '                    if 0<=nr<rows and 0<=nc<cols and grid[nr][nc]==1:',
    '                        grid[nr][nc]=2; fresh-=1; q.append((nr,nc))',
    '        return minutes if fresh==0 else -1',
    '',
    'if __name__ == "__main__":',
    '    grid_orig=[[2,1,1],[1,1,0],[0,1,1]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        g=copy.deepcopy(grid_orig)',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().orangesRotting(g)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: minutes={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0994_rotting_oranges.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 994: Rotting Oranges - Medium */',
    'int main(){',
    '    vector<vector<int>> g={{2,1,1},{1,1,0},{0,1,1}};',
    '    int rows=g.size(),cols=g[0].size(),fresh=0;',
    '    deque<tuple<int,int,int>> q;',
    '    for(int r=0;r<rows;r++) for(int c=0;c<cols;c++){ if(g[r][c]==2) q.push_back({r,c,0}); else if(g[r][c]==1) fresh++; }',
    '    auto s=chrono::high_resolution_clock::now();',
    '    int tmax=0;',
    '    while(!q.empty()){ auto[r,c,t]=q.front(); q.pop_front(); tmax=max(tmax,t); int dr[]={1,-1,0,0},dc[]={0,0,1,-1}; for(int d=0;d<4;d++){ int nr=r+dr[d],nc=c+dc[d]; if(nr>=0&&nr<rows&&nc>=0&&nc<cols&&g[nr][nc]==1){g[nr][nc]=2;fresh--;q.push_back({nr,nc,t+1});} } }',
    '    cout<<"var1: "<<(fresh==0?tmax:-1)<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 207. Course Schedule
write(f"{BASE}/11_graphs/0207_course_schedule.py", [
    '"""LeetCode 207: Course Schedule - Medium"""',
    'import time, tracemalloc',
    'from collections import defaultdict, deque',
    '',
    '# Variation 1: DFS cycle detection',
    'class Solution_v1:',
    '    def canFinish(self, numCourses: int, prerequisites) -> bool:',
    '        graph = defaultdict(list)',
    '        for c,p in prerequisites: graph[c].append(p)',
    '        # 0=unvisited, 1=in-stack, 2=done',
    '        state = [0]*numCourses',
    '        def dfs(c):',
    '            if state[c]==1: return False  # cycle',
    '            if state[c]==2: return True',
    '            state[c]=1',
    '            for nb in graph[c]:',
    '                if not dfs(nb): return False',
    '            state[c]=2; return True',
    '        return all(dfs(c) for c in range(numCourses))',
    '',
    '# Variation 2: Topological sort (Kahn BFS)',
    'class Solution_v2:',
    '    def canFinish(self, numCourses: int, prerequisites) -> bool:',
    '        graph = defaultdict(list); indeg = [0]*numCourses',
    '        for c,p in prerequisites: graph[p].append(c); indeg[c]+=1',
    '        q = deque([i for i in range(numCourses) if indeg[i]==0])',
    '        done = 0',
    '        while q:',
    '            c = q.popleft(); done+=1',
    '            for nb in graph[c]:',
    '                indeg[nb]-=1',
    '                if indeg[nb]==0: q.append(nb)',
    '        return done==numCourses',
    '',
    'if __name__ == "__main__":',
    '    prereqs=[[1,0],[2,0],[3,1],[3,2]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().canFinish(4, prereqs)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: can_finish={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0207_course_schedule.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 207: Course Schedule - Medium */',
    '// var1: DFS cycle detection',
    'bool dfs(int c, vector<vector<int>>& g, vector<int>& st){ if(st[c]==1) return false; if(st[c]==2) return true; st[c]=1; for(int nb:g[c]) if(!dfs(nb,g,st)) return false; st[c]=2; return true; }',
    'int main(){',
    '    int n=4; vector<pair<int,int>> pre={{1,0},{2,0},{3,1},{3,2}};',
    '    vector<vector<int>> g(n); for(auto[c,p]:pre) g[c].push_back(p);',
    '    auto s=chrono::high_resolution_clock::now();',
    '    vector<int> st(n,0); bool ok=true; for(int i=0;i<n&&ok;i++) ok=dfs(i,g,st);',
    '    cout<<"var1: can_finish="<<ok<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 210. Course Schedule II
write(f"{BASE}/11_graphs/0210_course_schedule_ii.py", [
    '"""LeetCode 210: Course Schedule II - Medium"""',
    'import time, tracemalloc',
    'from collections import defaultdict, deque',
    '',
    '# Variation 1: Kahn topological sort (BFS)',
    'class Solution_v1:',
    '    def findOrder(self, numCourses, prerequisites):',
    '        graph=defaultdict(list); indeg=[0]*numCourses',
    '        for c,p in prerequisites: graph[p].append(c); indeg[c]+=1',
    '        q=deque([i for i in range(numCourses) if indeg[i]==0]); order=[]',
    '        while q:',
    '            c=q.popleft(); order.append(c)',
    '            for nb in graph[c]:',
    '                indeg[nb]-=1',
    '                if indeg[nb]==0: q.append(nb)',
    '        return order if len(order)==numCourses else []',
    '',
    '# Variation 2: DFS post-order topological sort',
    'class Solution_v2:',
    '    def findOrder(self, numCourses, prerequisites):',
    '        graph=defaultdict(list)',
    '        for c,p in prerequisites: graph[c].append(p)',
    '        state=[0]*numCourses; order=[]',
    '        def dfs(c):',
    '            if state[c]==1: return False',
    '            if state[c]==2: return True',
    '            state[c]=1',
    '            for nb in graph[c]:',
    '                if not dfs(nb): return False',
    '            state[c]=2; order.append(c); return True',
    '        for c in range(numCourses):',
    '            if not dfs(c): return []',
    '        return order',
    '',
    'if __name__ == "__main__":',
    '    prereqs=[[1,0],[2,0],[3,1],[3,2]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().findOrder(4, prereqs)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: order={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0210_course_schedule_ii.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 210: Course Schedule II - Medium */',
    'int main(){',
    '    int n=4; vector<pair<int,int>> pre={{1,0},{2,0},{3,1},{3,2}};',
    '    vector<vector<int>> g(n); vector<int> indeg(n,0);',
    '    for(auto[c,p]:pre){g[p].push_back(c);indeg[c]++;}',
    '    auto s=chrono::high_resolution_clock::now();',
    '    queue<int> q; for(int i=0;i<n;i++) if(indeg[i]==0) q.push(i);',
    '    vector<int> order;',
    '    while(!q.empty()){int c=q.front();q.pop();order.push_back(c);for(int nb:g[c]){indeg[nb]--;if(indeg[nb]==0)q.push(nb);}}',
    '    cout<<"var1: order_size="<<order.size()<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 323. Number of Connected Components
write(f"{BASE}/11_graphs/0323_number_of_connected_components.py", [
    '"""LeetCode 323: Number of Connected Components - Medium"""',
    'import time, tracemalloc',
    'from collections import defaultdict',
    '',
    '# Variation 1: Union Find',
    'class Solution_v1:',
    '    def countComponents(self, n: int, edges) -> int:',
    '        parent=list(range(n)); rank=[0]*n',
    '        def find(x):',
    '            while parent[x]!=x: parent[x]=parent[parent[x]]; x=parent[x]',
    '            return x',
    '        count=n',
    '        for a,b in edges:',
    '            pa,pb=find(a),find(b)',
    '            if pa==pb: continue',
    '            if rank[pa]<rank[pb]: pa,pb=pb,pa',
    '            parent[pb]=pa',
    '            if rank[pa]==rank[pb]: rank[pa]+=1',
    '            count-=1',
    '        return count',
    '',
    '# Variation 2: DFS',
    'class Solution_v2:',
    '    def countComponents(self, n: int, edges) -> int:',
    '        graph=defaultdict(list)',
    '        for a,b in edges: graph[a].append(b); graph[b].append(a)',
    '        visited=set(); count=0',
    '        def dfs(node):',
    '            visited.add(node)',
    '            for nb in graph[node]:',
    '                if nb not in visited: dfs(nb)',
    '        for i in range(n):',
    '            if i not in visited: count+=1; dfs(i)',
    '        return count',
    '',
    'if __name__ == "__main__":',
    '    edges=[[0,1],[1,2],[3,4]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().countComponents(5,edges)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: components={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0323_number_of_connected_components.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 323: Number of Connected Components - Medium */',
    'int par[100],rnk[100];',
    'int find(int x){while(par[x]!=x){par[x]=par[par[x]];x=par[x];}return x;}',
    'int main(){',
    '    int n=5; vector<pair<int,int>> edges={{0,1},{1,2},{3,4}};',
    '    for(int i=0;i<n;i++){par[i]=i;rnk[i]=0;}',
    '    auto s=chrono::high_resolution_clock::now();',
    '    int cnt=n;',
    '    for(auto[a,b]:edges){int pa=find(a),pb=find(b);if(pa==pb)continue;if(rnk[pa]<rnk[pb])swap(pa,pb);par[pb]=pa;if(rnk[pa]==rnk[pb])rnk[pa]++;cnt--;}',
    '    cout<<"var1: components="<<cnt<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 261. Graph Valid Tree
write(f"{BASE}/11_graphs/0261_graph_valid_tree.py", [
    '"""LeetCode 261: Graph Valid Tree - Medium"""',
    'import time, tracemalloc',
    'from collections import defaultdict',
    '',
    '# Variation 1: Union Find (valid tree = n-1 edges, no cycle)',
    'class Solution_v1:',
    '    def validTree(self, n: int, edges) -> bool:',
    '        if len(edges)!=n-1: return False',
    '        parent=list(range(n))',
    '        def find(x):',
    '            while parent[x]!=x: parent[x]=parent[parent[x]]; x=parent[x]',
    '            return x',
    '        for a,b in edges:',
    '            pa,pb=find(a),find(b)',
    '            if pa==pb: return False',
    '            parent[pb]=pa',
    '        return True',
    '',
    '# Variation 2: DFS cycle detection',
    'class Solution_v2:',
    '    def validTree(self, n: int, edges) -> bool:',
    '        if len(edges)!=n-1: return False',
    '        graph=defaultdict(list)',
    '        for a,b in edges: graph[a].append(b); graph[b].append(a)',
    '        visited=set()',
    '        def dfs(node, parent):',
    '            if node in visited: return False',
    '            visited.add(node)',
    '            for nb in graph[node]:',
    '                if nb==parent: continue',
    '                if not dfs(nb,node): return False',
    '            return True',
    '        return dfs(0,-1) and len(visited)==n',
    '',
    'if __name__ == "__main__":',
    '    edges=[[0,1],[0,2],[0,3],[1,4]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().validTree(5,edges)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: valid_tree={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0261_graph_valid_tree.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 261: Graph Valid Tree - Medium */',
    'int par2[100];',
    'int find2(int x){while(par2[x]!=x){par2[x]=par2[par2[x]];x=par2[x];}return x;}',
    'int main(){',
    '    int n=5; vector<pair<int,int>> edges={{0,1},{0,2},{0,3},{1,4}};',
    '    if((int)edges.size()!=n-1){cout<<"var1: false"<<endl;return 0;}',
    '    for(int i=0;i<n;i++) par2[i]=i;',
    '    auto s=chrono::high_resolution_clock::now();',
    '    bool ok=true;',
    '    for(auto[a,b]:edges){int pa=find2(a),pb=find2(b);if(pa==pb){ok=false;break;}par2[pb]=pa;}',
    '    cout<<"var1: valid_tree="<<ok<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 684. Redundant Connection
write(f"{BASE}/11_graphs/0684_redundant_connection.py", [
    '"""LeetCode 684: Redundant Connection - Medium"""',
    'import time, tracemalloc',
    'from typing import List',
    '',
    '# Variation 1: Union Find - first edge that creates cycle',
    'class Solution_v1:',
    '    def findRedundantConnection(self, edges: List[List[int]]) -> List[int]:',
    '        parent=list(range(len(edges)+1)); rank=[0]*(len(edges)+1)',
    '        def find(x):',
    '            while parent[x]!=x: parent[x]=parent[parent[x]]; x=parent[x]',
    '            return x',
    '        for a,b in edges:',
    '            pa,pb=find(a),find(b)',
    '            if pa==pb: return [a,b]',
    '            if rank[pa]<rank[pb]: pa,pb=pb,pa',
    '            parent[pb]=pa',
    '            if rank[pa]==rank[pb]: rank[pa]+=1',
    '        return []',
    '',
    '# Variation 2: DFS - check if path exists before adding edge',
    'class Solution_v2:',
    '    def findRedundantConnection(self, edges: List[List[int]]) -> List[int]:',
    '        from collections import defaultdict',
    '        graph=defaultdict(set)',
    '        def dfs(src, dst, visited):',
    '            if src==dst: return True',
    '            visited.add(src)',
    '            for nb in graph[src]:',
    '                if nb not in visited and dfs(nb,dst,visited): return True',
    '            return False',
    '        for a,b in edges:',
    '            if dfs(a,b,set()): return [a,b]',
    '            graph[a].add(b); graph[b].add(a)',
    '        return []',
    '',
    'if __name__ == "__main__":',
    '    edges=[[1,2],[1,3],[2,3]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().findRedundantConnection(edges)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: redundant={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0684_redundant_connection.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 684: Redundant Connection - Medium */',
    'int par3[1001],rnk3[1001];',
    'int find3(int x){while(par3[x]!=x){par3[x]=par3[par3[x]];x=par3[x];}return x;}',
    'int main(){',
    '    vector<pair<int,int>> edges={{1,2},{1,3},{2,3}};',
    '    for(int i=0;i<=1000;i++){par3[i]=i;rnk3[i]=0;}',
    '    auto s=chrono::high_resolution_clock::now();',
    '    pair<int,int> ans={-1,-1};',
    '    for(auto[a,b]:edges){int pa=find3(a),pb=find3(b);if(pa==pb){ans={a,b};break;}if(rnk3[pa]<rnk3[pb])swap(pa,pb);par3[pb]=pa;if(rnk3[pa]==rnk3[pb])rnk3[pa]++;}',
    '    cout<<"var1: redundant=["<<ans.first<<","<<ans.second<<"]"<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 127. Word Ladder
write(f"{BASE}/11_graphs/0127_word_ladder.py", [
    '"""LeetCode 127: Word Ladder - Hard"""',
    'import time, tracemalloc',
    'from collections import deque, defaultdict',
    '',
    '# Variation 1: BFS one-directional',
    'class Solution_v1:',
    '    def ladderLength(self, beginWord: str, endWord: str, wordList) -> int:',
    '        wordSet=set(wordList)',
    '        if endWord not in wordSet: return 0',
    '        q=deque([(beginWord,1)])',
    '        while q:',
    '            word,steps=q.popleft()',
    '            for i in range(len(word)):',
    '                for c in "abcdefghijklmnopqrstuvwxyz":',
    '                    nw=word[:i]+c+word[i+1:]',
    '                    if nw==endWord: return steps+1',
    '                    if nw in wordSet: wordSet.remove(nw); q.append((nw,steps+1))',
    '        return 0',
    '',
    '# Variation 2: Bidirectional BFS (faster in practice)',
    'class Solution_v2:',
    '    def ladderLength(self, beginWord: str, endWord: str, wordList) -> int:',
    '        wordSet=set(wordList)',
    '        if endWord not in wordSet: return 0',
    '        front,back={beginWord},{endWord}',
    '        steps=1',
    '        while front:',
    '            if len(front)>len(back): front,back=back,front',
    '            nxt=set()',
    '            for word in front:',
    '                for i in range(len(word)):',
    '                    for c in "abcdefghijklmnopqrstuvwxyz":',
    '                        nw=word[:i]+c+word[i+1:]',
    '                        if nw in back: return steps+1',
    '                        if nw in wordSet: wordSet.discard(nw); nxt.add(nw)',
    '            front=nxt; steps+=1',
    '        return 0',
    '',
    '# Variation 3: BFS with adjacency preprocessing',
    'class Solution_v3:',
    '    def ladderLength(self, beginWord: str, endWord: str, wordList) -> int:',
    '        wordSet=set(wordList)',
    '        if endWord not in wordSet: return 0',
    '        adj=defaultdict(list)',
    '        for w in wordList+[beginWord]:',
    '            for i in range(len(w)): adj[w[:i]+"*"+w[i+1:]].append(w)',
    '        q=deque([(beginWord,1)]); visited={beginWord}',
    '        while q:',
    '            word,steps=q.popleft()',
    '            for i in range(len(word)):',
    '                pat=word[:i]+"*"+word[i+1:]',
    '                for nb in adj[pat]:',
    '                    if nb==endWord: return steps+1',
    '                    if nb not in visited: visited.add(nb); q.append((nb,steps+1))',
    '        return 0',
    '',
    'if __name__ == "__main__":',
    '    wl=["hot","dot","dog","lot","log","cog"]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2,Solution_v3],1):',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        r=Cls().ladderLength("hit","cog",wl[:])',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: length={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
    '# var3 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0127_word_ladder.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 127: Word Ladder - Hard */',
    'int main(){',
    '    string begin="hit",end_w="cog";',
    '    unordered_set<string> ws={"hot","dot","dog","lot","log","cog"};',
    '    auto s=chrono::high_resolution_clock::now();',
    '    if(!ws.count(end_w)){cout<<"var1: 0"<<endl;return 0;}',
    '    queue<pair<string,int>> q; q.push({begin,1});',
    '    while(!q.empty()){',
    '        auto[word,steps]=q.front();q.pop();',
    '        for(int i=0;i<(int)word.size();i++){',
    '            string nw=word;',
    '            for(char c=\'a\';c<=\'z\';c++){',
    '                nw[i]=c;',
    '                if(nw==end_w){cout<<"var1: "<<steps+1<<endl; auto e=chrono::high_resolution_clock::now(); cout<<"v1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl; return 0;}',
    '                if(ws.count(nw)){ws.erase(nw);q.push({nw,steps+1});}',
    '            }',
    '        }',
    '    }',
    '    cout<<"var1: 0"<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 130. Surrounded Regions
write(f"{BASE}/11_graphs/0130_surrounded_regions.py", [
    '"""LeetCode 130: Surrounded Regions - Medium"""',
    'import time, tracemalloc',
    'from typing import List',
    'import copy',
    '',
    '# Variation 1: DFS mark border-connected O first',
    'class Solution_v1:',
    '    def solve(self, board: List[List[str]]) -> None:',
    '        rows,cols=len(board),len(board[0])',
    '        def dfs(r,c):',
    '            if r<0 or r>=rows or c<0 or c>=cols or board[r][c]!="O": return',
    '            board[r][c]="T"',
    '            dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1)',
    '        for r in range(rows):',
    '            for c in [0,cols-1]: dfs(r,c)',
    '        for c in range(cols):',
    '            for r in [0,rows-1]: dfs(r,c)',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if board[r][c]=="O": board[r][c]="X"',
    '                elif board[r][c]=="T": board[r][c]="O"',
    '',
    '# Variation 2: Union Find - union border O with virtual node',
    'class Solution_v2:',
    '    def solve(self, board: List[List[str]]) -> None:',
    '        if not board: return',
    '        rows,cols=len(board),len(board[0])',
    '        dummy=rows*cols',
    '        parent=list(range(rows*cols+1))',
    '        def find(x):',
    '            while parent[x]!=x: parent[x]=parent[parent[x]]; x=parent[x]',
    '            return x',
    '        def union(a,b): parent[find(a)]=find(b)',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if board[r][c]=="O":',
    '                    if r==0 or r==rows-1 or c==0 or c==cols-1: union(r*cols+c,dummy)',
    '                    else:',
    '                        for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
    '                            if board[r+dr][c+dc]=="O": union(r*cols+c,(r+dr)*cols+(c+dc))',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if board[r][c]=="O" and find(r*cols+c)!=find(dummy): board[r][c]="X"',
    '',
    'if __name__ == "__main__":',
    '    board_orig=[["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        b=copy.deepcopy(board_orig)',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        Cls().solve(b)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: {b}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0130_surrounded_regions.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 130: Surrounded Regions - Medium */',
    'int RR,CC; vector<vector<char>>* BB;',
    'void dfs2(int r,int c){ if(r<0||r>=RR||c<0||c>=CC||(*BB)[r][c]!=\'O\') return; (*BB)[r][c]=\'T\'; dfs2(r+1,c);dfs2(r-1,c);dfs2(r,c+1);dfs2(r,c-1); }',
    'int main(){',
    '    vector<vector<char>> b={{\'X\',\'X\',\'X\',\'X\'},{\'X\',\'O\',\'O\',\'X\'},{\'X\',\'X\',\'O\',\'X\'},{\'X\',\'O\',\'X\',\'X\'}};',
    '    BB=&b; RR=b.size(); CC=b[0].size();',
    '    auto s=chrono::high_resolution_clock::now();',
    '    for(int r=0;r<RR;r++){dfs2(r,0);dfs2(r,CC-1);}',
    '    for(int c=0;c<CC;c++){dfs2(0,c);dfs2(RR-1,c);}',
    '    for(int r=0;r<RR;r++) for(int c=0;c<CC;c++){ if(b[r][c]==\'O\') b[r][c]=\'X\'; else if(b[r][c]==\'T\') b[r][c]=\'O\'; }',
    '    cout<<"var1 done"<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

# 286. Walls and Gates
write(f"{BASE}/11_graphs/0286_walls_and_gates.py", [
    '"""LeetCode 286: Walls and Gates (Fill Rooms) - Medium"""',
    'import time, tracemalloc',
    'from collections import deque',
    'from typing import List',
    'import copy',
    '',
    'INF = 2147483647',
    '',
    '# Variation 1: Multi-source BFS from gates',
    'class Solution_v1:',
    '    def wallsAndGates(self, rooms: List[List[int]]) -> None:',
    '        if not rooms: return',
    '        rows,cols=len(rooms),len(rooms[0]); q=deque()',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if rooms[r][c]==0: q.append((r,c))',
    '        while q:',
    '            r,c=q.popleft()',
    '            for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
    '                nr,nc=r+dr,c+dc',
    '                if 0<=nr<rows and 0<=nc<cols and rooms[nr][nc]==INF:',
    '                    rooms[nr][nc]=rooms[r][c]+1; q.append((nr,nc))',
    '',
    '# Variation 2: DFS from each gate',
    'class Solution_v2:',
    '    def wallsAndGates(self, rooms: List[List[int]]) -> None:',
    '        rows,cols=len(rooms),len(rooms[0])',
    '        def dfs(r,c,dist):',
    '            if r<0 or r>=rows or c<0 or c>=cols or rooms[r][c]<dist: return',
    '            rooms[r][c]=dist',
    '            dfs(r+1,c,dist+1);dfs(r-1,c,dist+1);dfs(r,c+1,dist+1);dfs(r,c-1,dist+1)',
    '        for r in range(rows):',
    '            for c in range(cols):',
    '                if rooms[r][c]==0: dfs(r,c,0)',
    '',
    'if __name__ == "__main__":',
    '    grid_orig=[[INF,-1,0,INF],[INF,INF,INF,-1],[INF,-1,INF,-1],[0,-1,INF,INF]]',
    '    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
    '        g=copy.deepcopy(grid_orig)',
    '        tracemalloc.start(); t0=time.perf_counter()',
    '        Cls().wallsAndGates(g)',
    '        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
    '        print(f"var{Vi}: done, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
    '# var1 mem = {} and time = {}',
    '# var2 mem = {} and time = {}',
])

write(f"{BASE}/11_graphs/0286_walls_and_gates.cpp", [
    '#include <bits/stdc++.h>',
    '#include <chrono>',
    'using namespace std;',
    '/* LeetCode 286: Walls and Gates - Medium */',
    'const int WINF=2147483647;',
    'int main(){',
    '    vector<vector<int>> g={{WINF,-1,0,WINF},{WINF,WINF,WINF,-1},{WINF,-1,WINF,-1},{0,-1,WINF,WINF}};',
    '    int rows=g.size(),cols=g[0].size();',
    '    deque<pair<int,int>> q;',
    '    for(int r=0;r<rows;r++) for(int c=0;c<cols;c++) if(g[r][c]==0) q.push_back({r,c});',
    '    auto s=chrono::high_resolution_clock::now();',
    '    int dr[]={1,-1,0,0},dc[]={0,0,1,-1};',
    '    while(!q.empty()){auto[r,c]=q.front();q.pop_front();for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<rows&&nc>=0&&nc<cols&&g[nr][nc]==WINF){g[nr][nc]=g[r][c]+1;q.push_back({nr,nc});}}}',
    '    cout<<"var1 done"<<endl;',
    '    auto e=chrono::high_resolution_clock::now();',
    '    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
    '}',
    '// var1 mem = {} and time = {}',
])

print("Section 11 graphs done!")
print(f"Files written to {BASE}/11_graphs/")
