#!/usr/bin/env python3
"""Generator for Section 13: 1D Dynamic Programming"""
import os
BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"
def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f: f.write('\n'.join(lines) + '\n')

# 70. Climbing Stairs
write(f"{BASE}/13_1d_dp/0070_climbing_stairs.py", [
'"""LeetCode 70: Climbing Stairs - Easy"""',
'import time, tracemalloc',
'',
'# Variation 1: DP bottom-up O(n)',
'class Solution_v1:',
'    def climbStairs(self, n: int) -> int:',
'        if n<=2: return n',
'        a,b=1,2',
'        for _ in range(3,n+1): a,b=b,a+b',
'        return b',
'',
'# Variation 2: Memoized recursion',
'class Solution_v2:',
'    def climbStairs(self, n: int) -> int:',
'        from functools import lru_cache',
'        @lru_cache(None)',
'        def dp(i): return i if i<=2 else dp(i-1)+dp(i-2)',
'        return dp(n)',
'',
'# Variation 3: Matrix exponentiation O(log n)',
'class Solution_v3:',
'    def climbStairs(self, n: int) -> int:',
'        def mat_mul(A,B):',
'            return [[A[0][0]*B[0][0]+A[0][1]*B[1][0], A[0][0]*B[0][1]+A[0][1]*B[1][1]],',
'                    [A[1][0]*B[0][0]+A[1][1]*B[1][0], A[1][0]*B[0][1]+A[1][1]*B[1][1]]]',
'        def mat_pow(M,p):',
'            result=[[1,0],[0,1]]',
'            while p:',
'                if p%2: result=mat_mul(result,M)',
'                M=mat_mul(M,M); p//=2',
'            return result',
'        M=[[1,1],[1,0]]',
'        return mat_pow(M,n)[0][0]',
'',
'if __name__ == "__main__":',
'    n=10',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2,Solution_v3],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().climbStairs(n)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: ways={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
'# var3 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0070_climbing_stairs.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 70: Climbing Stairs - Easy */',
'int main(){',
'    int n=10;',
'    auto s=chrono::high_resolution_clock::now();',
'    int a=1,b=2;',
'    for(int i=3;i<=n;i++){int c=a+b;a=b;b=c;}',
'    cout<<"var1: "<<b<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 746. Min Cost Climbing Stairs
write(f"{BASE}/13_1d_dp/0746_min_cost_climbing_stairs.py", [
'"""LeetCode 746: Min Cost Climbing Stairs - Easy"""',
'import time, tracemalloc',
'from typing import List',
'',
'# Variation 1: DP in-place',
'class Solution_v1:',
'    def minCostClimbingStairs(self, cost: List[int]) -> int:',
'        n=len(cost)',
'        for i in range(2,n): cost[i]+=min(cost[i-1],cost[i-2])',
'        return min(cost[-1],cost[-2])',
'',
'# Variation 2: DP with extra space',
'class Solution_v2:',
'    def minCostClimbingStairs(self, cost: List[int]) -> int:',
'        n=len(cost); dp=[0]*(n+1)',
'        for i in range(2,n+1): dp[i]=min(dp[i-1]+cost[i-1],dp[i-2]+cost[i-2])',
'        return dp[n]',
'',
'if __name__ == "__main__":',
'    import copy; cost=[10,15,20]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        c=copy.deepcopy(cost)',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().minCostClimbingStairs(c)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: cost={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0746_min_cost_climbing_stairs.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 746: Min Cost Climbing Stairs - Easy */',
'int main(){',
'    vector<int> cost={10,15,20,5,12,7,3,8}; int n=cost.size();',
'    auto s=chrono::high_resolution_clock::now();',
'    for(int i=2;i<n;i++) cost[i]+=min(cost[i-1],cost[i-2]);',
'    cout<<"var1: "<<min(cost[n-1],cost[n-2])<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 198. House Robber
write(f"{BASE}/13_1d_dp/0198_house_robber.py", [
'"""LeetCode 198: House Robber - Medium"""',
'import time, tracemalloc',
'from typing import List',
'',
'# Variation 1: DP two-variable',
'class Solution_v1:',
'    def rob(self, nums: List[int]) -> int:',
'        prev2,prev1=0,0',
'        for n in nums: prev2,prev1=prev1,max(prev1,prev2+n)',
'        return prev1',
'',
'# Variation 2: DP array',
'class Solution_v2:',
'    def rob(self, nums: List[int]) -> int:',
'        if not nums: return 0',
'        n=len(nums); dp=[0]*(n+1); dp[1]=nums[0]',
'        for i in range(2,n+1): dp[i]=max(dp[i-1],dp[i-2]+nums[i-1])',
'        return dp[n]',
'',
'# Variation 3: Recursion + memo',
'class Solution_v3:',
'    def rob(self, nums: List[int]) -> int:',
'        from functools import lru_cache',
'        @lru_cache(None)',
'        def dp(i): return 0 if i>=len(nums) else max(dp(i+1),nums[i]+dp(i+2))',
'        return dp(0)',
'',
'if __name__ == "__main__":',
'    nums=[2,7,9,3,1]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2,Solution_v3],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().rob(nums[:])',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: rob={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
'# var3 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0198_house_robber.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 198: House Robber - Medium */',
'int main(){',
'    vector<int> nums={2,7,9,3,1};',
'    auto s=chrono::high_resolution_clock::now();',
'    int a=0,b=0;',
'    for(int x:nums){int c=max(b,a+x);a=b;b=c;}',
'    cout<<"var1: "<<b<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 213. House Robber II
write(f"{BASE}/13_1d_dp/0213_house_robber_ii.py", [
'"""LeetCode 213: House Robber II - Medium"""',
'import time, tracemalloc',
'from typing import List',
'',
'def rob_linear(nums):',
'    prev2,prev1=0,0',
'    for n in nums: prev2,prev1=prev1,max(prev1,prev2+n)',
'    return prev1',
'',
'# Variation 1: Two passes (skip first / skip last)',
'class Solution_v1:',
'    def rob(self, nums: List[int]) -> int:',
'        if len(nums)==1: return nums[0]',
'        return max(rob_linear(nums[:-1]), rob_linear(nums[1:]))',
'',
'if __name__ == "__main__":',
'    nums=[2,3,2]',
'    tracemalloc.start(); t0=time.perf_counter()',
'    r=Solution_v1().rob(nums)',
'    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'    print(f"var1: rob={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0213_house_robber_ii.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 213: House Robber II - Medium */',
'int robLinear(vector<int>& n,int l,int r){int a=0,b=0;for(int i=l;i<=r;i++){int c=max(b,a+n[i]);a=b;b=c;}return b;}',
'int main(){',
'    vector<int> nums={2,3,2}; int n=nums.size();',
'    auto s=chrono::high_resolution_clock::now();',
'    int res=n==1?nums[0]:max(robLinear(nums,0,n-2),robLinear(nums,1,n-1));',
'    cout<<"var1: "<<res<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 5. Longest Palindromic Substring
write(f"{BASE}/13_1d_dp/0005_longest_palindromic_substring.py", [
'"""LeetCode 5: Longest Palindromic Substring - Medium"""',
'import time, tracemalloc',
'',
'# Variation 1: Expand around center O(n^2)',
'class Solution_v1:',
'    def longestPalindrome(self, s: str) -> str:',
'        res=""',
'        def expand(l,r):',
'            nonlocal res',
'            while l>=0 and r<len(s) and s[l]==s[r]: l-=1;r+=1',
'            if r-l-1>len(res): res=s[l+1:r]',
'        for i in range(len(s)): expand(i,i); expand(i,i+1)',
'        return res',
'',
'# Variation 2: DP table O(n^2)',
'class Solution_v2:',
'    def longestPalindrome(self, s: str) -> str:',
'        n=len(s); dp=[[False]*n for _ in range(n)]',
'        start,mx=0,1',
'        for i in range(n): dp[i][i]=True',
'        for i in range(n-1):',
'            if s[i]==s[i+1]: dp[i][i+1]=True; start=i; mx=2',
'        for length in range(3,n+1):',
'            for i in range(n-length+1):',
'                j=i+length-1',
'                if s[i]==s[j] and dp[i+1][j-1]: dp[i][j]=True; start=i; mx=length',
'        return s[start:start+mx]',
'',
'# Variation 3: Manacher O(n)',
'class Solution_v3:',
'    def longestPalindrome(self, s: str) -> str:',
'        t="$#"+"#".join(s)+"#@"; n=len(t)',
'        p=[0]*n; c=r=0',
'        for i in range(1,n-1):',
'            if i<r: p[i]=min(r-i,p[2*c-i])',
'            while t[i+p[i]+1]==t[i-p[i]-1]: p[i]+=1',
'            if i+p[i]>r: c,r=i,i+p[i]',
'        best=max(range(n),key=lambda i:p[i])',
'        return s[(best-p[best])//2:(best+p[best])//2]',
'',
'if __name__ == "__main__":',
'    s="babad"',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2,Solution_v3],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().longestPalindrome(s)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: {r!r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
'# var3 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0005_longest_palindromic_substring.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 5: Longest Palindromic Substring - Medium */',
'string expand(const string& s, int l, int r){ while(l>=0&&r<(int)s.size()&&s[l]==s[r]){l--;r++;} return s.substr(l+1,r-l-1); }',
'int main(){',
'    string s="babad";',
'    auto t=chrono::high_resolution_clock::now();',
'    string res="";',
'    for(int i=0;i<(int)s.size();i++){',
'        string a=expand(s,i,i),b=expand(s,i,i+1);',
'        if(a.size()>res.size()) res=a;',
'        if(b.size()>res.size()) res=b;',
'    }',
'    cout<<"var1: "<<res<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-s).count()/1000.0<<"us"<<endl; // Note: reusing s for time here',
'}',
'// var1 mem = {} and time = {}',
])

# 647. Palindromic Substrings
write(f"{BASE}/13_1d_dp/0647_palindromic_substrings.py", [
'"""LeetCode 647: Palindromic Substrings - Medium"""',
'import time, tracemalloc',
'',
'# Variation 1: Expand around center',
'class Solution_v1:',
'    def countSubstrings(self, s: str) -> int:',
'        count=0',
'        def expand(l,r):',
'            nonlocal count',
'            while l>=0 and r<len(s) and s[l]==s[r]: count+=1; l-=1; r+=1',
'        for i in range(len(s)): expand(i,i); expand(i,i+1)',
'        return count',
'',
'# Variation 2: DP table',
'class Solution_v2:',
'    def countSubstrings(self, s: str) -> int:',
'        n=len(s); dp=[[False]*n for _ in range(n)]; count=0',
'        for i in range(n-1,-1,-1):',
'            for j in range(i,n):',
'                if s[i]==s[j] and (j-i<=2 or dp[i+1][j-1]):',
'                    dp[i][j]=True; count+=1',
'        return count',
'',
'if __name__ == "__main__":',
'    s="aaa"',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().countSubstrings(s)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: count={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0647_palindromic_substrings.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 647: Palindromic Substrings - Medium */',
'int main(){',
'    string s="aaa"; int count=0;',
'    auto t=chrono::high_resolution_clock::now();',
'    for(int i=0;i<(int)s.size();i++){',
'        for(int l=i,r=i;l>=0&&r<(int)s.size()&&s[l]==s[r];l--,r++) count++;',
'        for(int l=i,r=i+1;l>=0&&r<(int)s.size()&&s[l]==s[r];l--,r++) count++;',
'    }',
'    cout<<"var1: "<<count<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 91. Decode Ways
write(f"{BASE}/13_1d_dp/0091_decode_ways.py", [
'"""LeetCode 91: Decode Ways - Medium"""',
'import time, tracemalloc',
'',
'# Variation 1: DP iterative',
'class Solution_v1:',
'    def numDecodings(self, s: str) -> int:',
'        n=len(s); dp=[0]*(n+1); dp[0]=1; dp[1]=0 if s[0]=="0" else 1',
'        for i in range(2,n+1):',
'            if s[i-1]!="0": dp[i]+=dp[i-1]',
'            two=int(s[i-2:i])',
'            if 10<=two<=26: dp[i]+=dp[i-2]',
'        return dp[n]',
'',
'# Variation 2: Recursion + memo',
'class Solution_v2:',
'    def numDecodings(self, s: str) -> int:',
'        from functools import lru_cache',
'        @lru_cache(None)',
'        def dp(i):',
'            if i==len(s): return 1',
'            if s[i]=="0": return 0',
'            res=dp(i+1)',
'            if i+1<len(s) and int(s[i:i+2])<=26: res+=dp(i+2)',
'            return res',
'        return dp(0)',
'',
'if __name__ == "__main__":',
'    s="226"',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().numDecodings(s)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: ways={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0091_decode_ways.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 91: Decode Ways - Medium */',
'int main(){',
'    string s="226"; int n=s.size();',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<int> dp(n+1,0); dp[0]=1; dp[1]=(s[0]!="0"[0])?1:0;',
'    for(int i=2;i<=n;i++){',
'        if(s[i-1]!="0") dp[i]+=dp[i-1];',
'        int two=stoi(s.substr(i-2,2));',
'        if(two>=10&&two<=26) dp[i]+=dp[i-2];',
'    }',
'    cout<<"var1: "<<dp[n]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 322. Coin Change
write(f"{BASE}/13_1d_dp/0322_coin_change.py", [
'"""LeetCode 322: Coin Change - Medium"""',
'import time, tracemalloc',
'from typing import List',
'',
'# Variation 1: BFS (level = amount, nodes = coins) O(amount*len(coins))',
'class Solution_v1:',
'    def coinChange(self, coins: List[int], amount: int) -> int:',
'        from collections import deque',
'        if amount==0: return 0',
'        q=deque([(0,0)]); visited={0}',
'        while q:',
'            cur,steps=q.popleft()',
'            for c in coins:',
'                nxt=cur+c',
'                if nxt==amount: return steps+1',
'                if nxt<amount and nxt not in visited: visited.add(nxt); q.append((nxt,steps+1))',
'        return -1',
'',
'# Variation 2: DP bottom-up',
'class Solution_v2:',
'    def coinChange(self, coins: List[int], amount: int) -> int:',
'        dp=[float("inf")]*(amount+1); dp[0]=0',
'        for a in range(1,amount+1):',
'            for c in coins:',
'                if c<=a: dp[a]=min(dp[a],dp[a-c]+1)',
'        return dp[amount] if dp[amount]!=float("inf") else -1',
'',
'# Variation 3: DFS + memo (top-down)',
'class Solution_v3:',
'    def coinChange(self, coins: List[int], amount: int) -> int:',
'        from functools import lru_cache',
'        @lru_cache(None)',
'        def dp(rem):',
'            if rem<0: return float("inf")',
'            if rem==0: return 0',
'            return 1+min(dp(rem-c) for c in coins)',
'        r=dp(amount)',
'        return r if r!=float("inf") else -1',
'',
'if __name__ == "__main__":',
'    coins=[1,5,11]; amount=15',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2,Solution_v3],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().coinChange(coins,amount)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: coins={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
'# var3 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0322_coin_change.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 322: Coin Change - Medium */',
'int main(){',
'    vector<int> coins={1,5,11}; int amount=15;',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<int> dp(amount+1,INT_MAX); dp[0]=0;',
'    for(int a=1;a<=amount;a++) for(int c:coins) if(c<=a&&dp[a-c]!=INT_MAX) dp[a]=min(dp[a],dp[a-c]+1);',
'    cout<<"var1: "<<(dp[amount]==INT_MAX?-1:dp[amount])<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 139. Word Break
write(f"{BASE}/13_1d_dp/0139_word_break.py", [
'"""LeetCode 139: Word Break - Medium"""',
'import time, tracemalloc',
'from typing import List',
'',
'# Variation 1: DP array',
'class Solution_v1:',
'    def wordBreak(self, s: str, wordDict: List[str]) -> bool:',
'        words=set(wordDict); n=len(s); dp=[False]*(n+1); dp[0]=True',
'        for i in range(1,n+1):',
'            for j in range(i):',
'                if dp[j] and s[j:i] in words: dp[i]=True; break',
'        return dp[n]',
'',
'# Variation 2: BFS',
'class Solution_v2:',
'    def wordBreak(self, s: str, wordDict: List[str]) -> bool:',
'        from collections import deque',
'        words=set(wordDict); q=deque([0]); visited=set()',
'        while q:',
'            start=q.popleft()',
'            if start==len(s): return True',
'            if start in visited: continue',
'            visited.add(start)',
'            for end in range(start+1,len(s)+1):',
'                if s[start:end] in words: q.append(end)',
'        return False',
'',
'if __name__ == "__main__":',
'    s="leetcode"; wd=["leet","code"]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().wordBreak(s,wd)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: can_break={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0139_word_break.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 139: Word Break - Medium */',
'int main(){',
'    string s="leetcode"; unordered_set<string> words={"leet","code"};',
'    int n=s.size();',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<bool> dp(n+1,false); dp[0]=true;',
'    for(int i=1;i<=n;i++) for(int j=0;j<i;j++) if(dp[j]&&words.count(s.substr(j,i-j))){dp[i]=true;break;}',
'    cout<<"var1: "<<dp[n]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 300. Longest Increasing Subsequence
write(f"{BASE}/13_1d_dp/0300_longest_increasing_subsequence.py", [
'"""LeetCode 300: LIS - Medium"""',
'import time, tracemalloc',
'import bisect',
'from typing import List',
'',
'# Variation 1: DP O(n^2)',
'class Solution_v1:',
'    def lengthOfLIS(self, nums: List[int]) -> int:',
'        dp=[1]*len(nums)',
'        for i in range(len(nums)):',
'            for j in range(i): ',
'                if nums[j]<nums[i]: dp[i]=max(dp[i],dp[j]+1)',
'        return max(dp)',
'',
'# Variation 2: Patience sort (binary search) O(n log n)',
'class Solution_v2:',
'    def lengthOfLIS(self, nums: List[int]) -> int:',
'        tails=[]',
'        for n in nums:',
'            pos=bisect.bisect_left(tails,n)',
'            if pos==len(tails): tails.append(n)',
'            else: tails[pos]=n',
'        return len(tails)',
'',
'if __name__ == "__main__":',
'    nums=[10,9,2,5,3,7,101,18]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().lengthOfLIS(nums)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: lis={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0300_longest_increasing_subsequence.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 300: LIS - Medium */',
'int main(){',
'    vector<int> nums={10,9,2,5,3,7,101,18};',
'    auto t=chrono::high_resolution_clock::now();',
'    // Patience sort O(n log n)',
'    vector<int> tails;',
'    for(int x:nums){ auto it=lower_bound(tails.begin(),tails.end(),x); if(it==tails.end()) tails.push_back(x); else *it=x; }',
'    cout<<"var1 (patience): "<<tails.size()<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 416. Partition Equal Subset Sum
write(f"{BASE}/13_1d_dp/0416_partition_equal_subset_sum.py", [
'"""LeetCode 416: Partition Equal Subset Sum - Medium"""',
'import time, tracemalloc',
'from typing import List',
'',
'# Variation 1: DP bitset / set of achievable sums',
'class Solution_v1:',
'    def canPartition(self, nums: List[int]) -> bool:',
'        total=sum(nums)',
'        if total%2: return False',
'        target=total//2; dp={0}',
'        for n in nums:',
'            dp={x+n for x in dp}|dp',
'        return target in dp',
'',
'# Variation 2: DP boolean array',
'class Solution_v2:',
'    def canPartition(self, nums: List[int]) -> bool:',
'        total=sum(nums)',
'        if total%2: return False',
'        target=total//2; dp=[False]*(target+1); dp[0]=True',
'        for n in nums:',
'            for j in range(target,n-1,-1):',
'                dp[j]=dp[j] or dp[j-n]',
'        return dp[target]',
'',
'if __name__ == "__main__":',
'    nums=[1,5,11,5]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().canPartition(nums)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: can_partition={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])

write(f"{BASE}/13_1d_dp/0416_partition_equal_subset_sum.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'/* LeetCode 416: Partition Equal Subset Sum - Medium */',
'int main(){',
'    vector<int> nums={1,5,11,5}; int total=accumulate(nums.begin(),nums.end(),0);',
'    if(total%2){cout<<"var1: false"<<endl;return 0;}',
'    int target=total/2;',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<bool> dp(target+1,false); dp[0]=true;',
'    for(int x:nums) for(int j=target;j>=x;j--) dp[j]=dp[j]||dp[j-x];',
'    cout<<"var1: "<<dp[target]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

print("Section 13 1D DP done!")
