#!/usr/bin/env python3
import os
BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"
def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f: f.write('\n'.join(lines) + '\n')

# 136. Single Number
write(f"{BASE}/18_bit_manipulation/0136_single_number.py", ['"""LeetCode 136: Single Number - Easy"""','import time, tracemalloc','from typing import List','# Variation 1: XOR','class Solution_v1:','    def singleNumber(self, nums: List[int]) -> int:','        res = 0','        for n in nums: res = n ^ res','        return res','# Variation 2: Hash Set','class Solution_v2:','    def singleNumber(self, nums: List[int]) -> int:','        return 2*sum(set(nums)) - sum(nums)','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().singleNumber([4,1,2,1,2])','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/18_bit_manipulation/0136_single_number.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<int> nums = {4,1,2,1,2};','    auto t=chrono::high_resolution_clock::now();','    int res = 0; for(int n: nums) res ^= n;','    cout<<"var1: "<<res<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 191. Number of 1 Bits
write(f"{BASE}/18_bit_manipulation/0191_number_of_1_bits.py", ['"""LeetCode 191: Number of 1 Bits - Easy"""','import time, tracemalloc','# Variation 1: Modulo and bit shift','class Solution_v1:','    def hammingWeight(self, n: int) -> int:','        res = 0','        while n:','            res += n % 2','            n = n >> 1','        return res','# Variation 2: n & (n - 1) trick','class Solution_v2:','    def hammingWeight(self, n: int) -> int:','        res = 0','        while n:','            n &= (n - 1)','            res += 1','        return res','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().hammingWeight(11)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/18_bit_manipulation/0191_number_of_1_bits.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    uint32_t n = 11;','    auto t=chrono::high_resolution_clock::now();','    int res = 0; while(n){ n &= (n - 1); res++; }','    cout<<"var1: "<<res<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 338. Counting Bits
write(f"{BASE}/18_bit_manipulation/0338_counting_bits.py", ['"""LeetCode 338: Counting Bits - Easy"""','import time, tracemalloc','from typing import List','# Variation 1: DP + Bit Shift','class Solution_v1:','    def countBits(self, n: int) -> List[int]:','        dp = [0] * (n + 1)','        offset = 1','        for i in range(1, n + 1):','            if offset * 2 == i: offset = i','            dp[i] = 1 + dp[i - offset]','        return dp','# Variation 2: n & (n - 1) DP','class Solution_v2:','    def countBits(self, n: int) -> List[int]:','        dp = [0] * (n + 1)','        for i in range(1, n + 1):','            dp[i] = dp[i & (i - 1)] + 1','        return dp','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().countBits(5)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/18_bit_manipulation/0338_counting_bits.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    int n = 5;','    auto t=chrono::high_resolution_clock::now();','    vector<int> dp(n + 1, 0);','    for(int i=1; i<=n; i++) dp[i] = dp[i & (i - 1)] + 1;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 268. Missing Number
write(f"{BASE}/18_bit_manipulation/0268_missing_number.py", ['"""LeetCode 268: Missing Number - Easy"""','import time, tracemalloc','from typing import List','# Variation 1: XOR','class Solution_v1:','    def missingNumber(self, nums: List[int]) -> int:','        res = len(nums)','        for i in range(len(nums)):','            res += (i - nums[i])','        return res','# Variation 2: Gauss formula','class Solution_v2:','    def missingNumber(self, nums: List[int]) -> int:','        res = len(nums)','        for i, n in enumerate(nums):','            res ^= i ^ n','        return res','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().missingNumber([3,0,1])','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}','# var2 mem = {} and time = {}'])
write(f"{BASE}/18_bit_manipulation/0268_missing_number.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    vector<int> nums = {3,0,1};','    auto t=chrono::high_resolution_clock::now();','    int res = nums.size();','    for(int i=0; i<nums.size(); i++) res ^= (i ^ nums[i]);','    cout<<"var1: "<<res<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 190. Reverse Bits
write(f"{BASE}/18_bit_manipulation/0190_reverse_bits.py", ['"""LeetCode 190: Reverse Bits - Easy"""','import time, tracemalloc','# Variation 1: Bit by bit','class Solution_v1:','    def reverseBits(self, n: int) -> int:','        res = 0','        for i in range(32):','            bit = (n >> i) & 1','            res = res | (bit << (31 - i))','        return res','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().reverseBits(43261596)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/18_bit_manipulation/0190_reverse_bits.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    uint32_t n = 43261596;','    auto t=chrono::high_resolution_clock::now();','    uint32_t res = 0;','    for(int i=0; i<32; i++){','        uint32_t bit = (n >> i) & 1;','        res = res | (bit << (31 - i));','    }','    cout<<"var1: "<<res<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 371. Sum of Two Integers
write(f"{BASE}/18_bit_manipulation/0371_sum_of_two_integers.py", ['"""LeetCode 371: Sum of Two Integers - Medium"""','import time, tracemalloc','# Variation 1: Python specific bit-manipulation with 32-bit mask','class Solution_v1:','    def getSum(self, a: int, b: int) -> int:','        mask = 0xFFFFFFFF','        while b != 0:','            tmp = (a & b) << 1','            a = (a ^ b) & mask','            b = tmp & mask','        if a > 0x7FFFFFFF: return ~(a ^ mask)','        return a','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().getSum(1, 2)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/18_bit_manipulation/0371_sum_of_two_integers.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    int a = 1, b = 2;','    auto t=chrono::high_resolution_clock::now();','    while(b != 0){','        int tmp = (a & b) << 1;','        a = a ^ b;','        b = tmp;','    }','    cout<<"var1: "<<a<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

# 7. Reverse Integer
write(f"{BASE}/18_bit_manipulation/0007_reverse_integer.py", ['"""LeetCode 7: Reverse Integer - Medium"""','import time, tracemalloc','import math','# Variation 1: Mod and division math','class Solution_v1:','    def reverse(self, x: int) -> int:','        MIN = -2147483648; MAX = 2147483647','        res = 0','        while x:','            digit = int(math.fmod(x, 10))','            x = int(x / 10)','            if res > MAX // 10 or (res == MAX // 10 and digit >= MAX % 10): return 0','            if res < MIN // 10 or (res == MIN // 10 and digit <= MIN % 10): return 0','            res = (res * 10) + digit','        return res','if __name__ == "__main__":','    for Vi,Cls in enumerate([Solution_v1],1):','        tracemalloc.start(); t0=time.perf_counter()','        r = Cls().reverse(123)','        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()','        print(f"var{Vi}: res={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")','# var1 mem = {} and time = {}'])
write(f"{BASE}/18_bit_manipulation/0007_reverse_integer.cpp", ['#include <bits/stdc++.h>','#include <chrono>','using namespace std;','int main(){','    int x = 123;','    auto t=chrono::high_resolution_clock::now();','    int res = 0;','    while(x){','        int digit = x % 10; x /= 10;','        if(res > INT_MAX / 10 || (res == INT_MAX / 10 && digit >= INT_MAX % 10)){ cout<<"var1: 0"<<endl; return 0; }','        if(res < INT_MIN / 10 || (res == INT_MIN / 10 && digit <= INT_MIN % 10)){ cout<<"var1: 0"<<endl; return 0; }','        res = (res * 10) + digit;','    }','    cout<<"var1: "<<res<<endl;','    auto e=chrono::high_resolution_clock::now();','    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;','}','// var1 mem = {} and time = {}'])

print("Section 18 done!")
