#!/usr/bin/env python3
"""Generator for Section 14: 2D Dynamic Programming"""
import os
BASE = "/media/pope/projecteo/github_proj/leetcode/neetcode150"
def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f: f.write('\n'.join(lines) + '\n')

# 62. Unique Paths
write(f"{BASE}/14_2d_dp/0062_unique_paths.py", [
'"""LeetCode 62: Unique Paths - Medium"""',
'import time, tracemalloc',
'# Variation 1: 2D DP',
'class Solution_v1:',
'    def uniquePaths(self, m, n):',
'        dp=[[1]*n for _ in range(m)]',
'        for r in range(1,m):',
'            for c in range(1,n): dp[r][c]=dp[r-1][c]+dp[r][c-1]',
'        return dp[m-1][n-1]',
'# Variation 2: 1D DP',
'class Solution_v2:',
'    def uniquePaths(self, m, n):',
'        dp=[1]*n',
'        for _ in range(1,m):',
'            for c in range(1,n): dp[c]+=dp[c-1]',
'        return dp[n-1]',
'# Variation 3: Math C(m+n-2, m-1)',
'class Solution_v3:',
'    def uniquePaths(self, m, n):',
'        from math import comb',
'        return comb(m+n-2, m-1)',
'if __name__ == "__main__":',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2,Solution_v3],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().uniquePaths(3,7)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: paths={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
'# var3 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0062_unique_paths.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    int m=3,n=7;',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<int> dp(n,1);',
'    for(int r=1;r<m;r++) for(int c=1;c<n;c++) dp[c]+=dp[c-1];',
'    cout<<"var1: "<<dp[n-1]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 1143. LCS
write(f"{BASE}/14_2d_dp/1143_longest_common_subsequence.py", [
'"""LeetCode 1143: Longest Common Subsequence - Medium"""',
'import time, tracemalloc',
'# Variation 1: 2D DP',
'class Solution_v1:',
'    def longestCommonSubsequence(self, t1, t2):',
'        m,n=len(t1),len(t2)',
'        dp=[[0]*(n+1) for _ in range(m+1)]',
'        for i in range(1,m+1):',
'            for j in range(1,n+1):',
'                if t1[i-1]==t2[j-1]: dp[i][j]=1+dp[i-1][j-1]',
'                else: dp[i][j]=max(dp[i-1][j],dp[i][j-1])',
'        return dp[m][n]',
'# Variation 2: 1D rolling array',
'class Solution_v2:',
'    def longestCommonSubsequence(self, t1, t2):',
'        m,n=len(t1),len(t2)',
'        prev,cur=[0]*(n+1),[0]*(n+1)',
'        for i in range(1,m+1):',
'            for j in range(1,n+1):',
'                if t1[i-1]==t2[j-1]: cur[j]=1+prev[j-1]',
'                else: cur[j]=max(prev[j],cur[j-1])',
'            prev,cur=cur,[0]*(n+1)',
'        return prev[n]',
'if __name__ == "__main__":',
'    a,b="abcde","ace"',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().longestCommonSubsequence(a,b)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: lcs={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/1143_longest_common_subsequence.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    string s1="abcde",s2="ace"; int m=s1.size(),n=s2.size();',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<vector<int>> dp(m+1,vector<int>(n+1,0));',
'    for(int i=1;i<=m;i++) for(int j=1;j<=n;j++) dp[i][j]=s1[i-1]==s2[j-1]?1+dp[i-1][j-1]:max(dp[i-1][j],dp[i][j-1]);',
'    cout<<"var1: "<<dp[m][n]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 309. Best Time to Buy Stock with Cooldown
write(f"{BASE}/14_2d_dp/0309_best_time_to_buy_and_sell_stock_with_cooldown.py", [
'"""LeetCode 309: Stock with Cooldown - Medium"""',
'import time, tracemalloc',
'from typing import List',
'# Variation 1: State machine DP (hold, sold, rest)',
'class Solution_v1:',
'    def maxProfit(self, prices: List[int]) -> int:',
'        hold,sold,rest=float("-inf"),0,0',
'        for p in prices:',
'            hold,sold,rest=max(hold,rest-p),hold+p,max(rest,sold)',
'        return max(sold,rest)',
'# Variation 2: Recursive memo',
'class Solution_v2:',
'    def maxProfit(self, prices: List[int]) -> int:',
'        from functools import lru_cache',
'        @lru_cache(None)',
'        def dp(i,holding):',
'            if i>=len(prices): return 0',
'            if holding:',
'                return max(dp(i+1,True), prices[i]+dp(i+2,False))',
'            return max(dp(i+1,False), dp(i+1,True)-prices[i])',
'        return dp(0,False)',
'if __name__ == "__main__":',
'    prices=[1,2,3,0,2]',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().maxProfit(prices)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: profit={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0309_best_time_to_buy_and_sell_stock_with_cooldown.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    vector<int> p={1,2,3,0,2};',
'    auto t=chrono::high_resolution_clock::now();',
'    int hold=INT_MIN,sold=0,rest=0;',
'    for(int x:p){int h=max(hold,rest-x),s=hold+x,r=max(rest,sold);hold=h;sold=s;rest=r;}',
'    cout<<"var1: "<<max(sold,rest)<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 518. Coin Change II
write(f"{BASE}/14_2d_dp/0518_coin_change_ii.py", [
'"""LeetCode 518: Coin Change II - Medium"""',
'import time, tracemalloc',
'from typing import List',
'# Variation 1: 1D DP (unbounded knapsack)',
'class Solution_v1:',
'    def change(self, amount: int, coins: List[int]) -> int:',
'        dp=[0]*(amount+1); dp[0]=1',
'        for c in coins:',
'            for a in range(c,amount+1): dp[a]+=dp[a-c]',
'        return dp[amount]',
'# Variation 2: 2D DP',
'class Solution_v2:',
'    def change(self, amount: int, coins: List[int]) -> int:',
'        m=len(coins); dp=[[0]*(amount+1) for _ in range(m+1)]',
'        for i in range(m+1): dp[i][0]=1',
'        for i in range(1,m+1):',
'            for a in range(amount+1):',
'                dp[i][a]=dp[i-1][a]',
'                if a>=coins[i-1]: dp[i][a]+=dp[i][a-coins[i-1]]',
'        return dp[m][amount]',
'if __name__ == "__main__":',
'    coins=[1,2,5]; amount=5',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().change(amount,coins)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: ways={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0518_coin_change_ii.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    vector<int> coins={1,2,5}; int amount=5;',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<long long> dp(amount+1,0); dp[0]=1;',
'    for(int c:coins) for(int a=c;a<=amount;a++) dp[a]+=dp[a-c];',
'    cout<<"var1: "<<dp[amount]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 494. Target Sum
write(f"{BASE}/14_2d_dp/0494_target_sum.py", [
'"""LeetCode 494: Target Sum - Medium"""',
'import time, tracemalloc',
'from typing import List',
'from collections import defaultdict',
'# Variation 1: DFS brute force O(2^n)',
'class Solution_v1:',
'    def findTargetSumWays(self, nums: List[int], target: int) -> int:',
'        def dfs(i, total):',
'            if i==len(nums): return 1 if total==target else 0',
'            return dfs(i+1,total+nums[i])+dfs(i+1,total-nums[i])',
'        return dfs(0,0)',
'# Variation 2: DP with hashmap',
'class Solution_v2:',
'    def findTargetSumWays(self, nums: List[int], target: int) -> int:',
'        dp=defaultdict(int); dp[0]=1',
'        for n in nums:',
'            ndp=defaultdict(int)',
'            for s,cnt in dp.items():',
'                ndp[s+n]+=cnt; ndp[s-n]+=cnt',
'            dp=ndp',
'        return dp[target]',
'if __name__ == "__main__":',
'    nums=[1,1,1,1,1]; target=3',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().findTargetSumWays(nums,target)',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: ways={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0494_target_sum.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    vector<int> nums={1,1,1,1,1}; int target=3;',
'    auto t=chrono::high_resolution_clock::now();',
'    unordered_map<int,int> dp; dp[0]=1;',
'    for(int n:nums){ unordered_map<int,int> nd; for(auto&[s,c]:dp){nd[s+n]+=c;nd[s-n]+=c;} dp=nd; }',
'    cout<<"var1: "<<dp[target]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 97. Interleaving String
write(f"{BASE}/14_2d_dp/0097_interleaving_string.py", [
'"""LeetCode 97: Interleaving String - Medium"""',
'import time, tracemalloc',
'# Variation 1: 2D DP',
'class Solution_v1:',
'    def isInterleave(self, s1, s2, s3) -> bool:',
'        m,n=len(s1),len(s2)',
'        if m+n!=len(s3): return False',
'        dp=[[False]*(n+1) for _ in range(m+1)]',
'        dp[0][0]=True',
'        for i in range(1,m+1): dp[i][0]=dp[i-1][0] and s1[i-1]==s3[i-1]',
'        for j in range(1,n+1): dp[0][j]=dp[0][j-1] and s2[j-1]==s3[j-1]',
'        for i in range(1,m+1):',
'            for j in range(1,n+1):',
'                dp[i][j]=(dp[i-1][j] and s1[i-1]==s3[i+j-1]) or (dp[i][j-1] and s2[j-1]==s3[i+j-1])',
'        return dp[m][n]',
'# Variation 2: BFS',
'class Solution_v2:',
'    def isInterleave(self, s1, s2, s3) -> bool:',
'        from collections import deque',
'        m,n=len(s1),len(s2)',
'        if m+n!=len(s3): return False',
'        q=deque([(0,0)]); seen=set()',
'        while q:',
'            i,j=q.popleft()',
'            if i+j==len(s3): return True',
'            if (i,j) in seen: continue',
'            seen.add((i,j))',
'            if i<m and s1[i]==s3[i+j]: q.append((i+1,j))',
'            if j<n and s2[j]==s3[i+j]: q.append((i,j+1))',
'        return False',
'if __name__ == "__main__":',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().isInterleave("aabcc","dbbca","aadbbcbcac")',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0097_interleaving_string.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    string s1="aabcc",s2="dbbca",s3="aadbbcbcac";',
'    int m=s1.size(),n=s2.size();',
'    auto t=chrono::high_resolution_clock::now();',
'    if(m+n!=(int)s3.size()){cout<<"var1: false"<<endl;return 0;}',
'    vector<vector<bool>> dp(m+1,vector<bool>(n+1,false));',
'    dp[0][0]=true;',
'    for(int i=1;i<=m;i++) dp[i][0]=dp[i-1][0]&&s1[i-1]==s3[i-1];',
'    for(int j=1;j<=n;j++) dp[0][j]=dp[0][j-1]&&s2[j-1]==s3[j-1];',
'    for(int i=1;i<=m;i++) for(int j=1;j<=n;j++) dp[i][j]=(dp[i-1][j]&&s1[i-1]==s3[i+j-1])||(dp[i][j-1]&&s2[j-1]==s3[i+j-1]);',
'    cout<<"var1: "<<dp[m][n]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 329. Longest Increasing Path in a Matrix
write(f"{BASE}/14_2d_dp/0329_longest_increasing_path_in_a_matrix.py", [
'"""LeetCode 329: Longest Increasing Path in a Matrix - Hard"""',
'import time, tracemalloc',
'from typing import List',
'from functools import lru_cache',
'# Variation 1: DFS + memo',
'class Solution_v1:',
'    def longestIncreasingPath(self, matrix: List[List[int]]) -> int:',
'        rows,cols=len(matrix),len(matrix[0])',
'        @lru_cache(None)',
'        def dfs(r,c):',
'            best=1',
'            for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:',
'                nr,nc=r+dr,c+dc',
'                if 0<=nr<rows and 0<=nc<cols and matrix[nr][nc]>matrix[r][c]:',
'                    best=max(best,1+dfs(nr,nc))',
'            return best',
'        return max(dfs(r,c) for r in range(rows) for c in range(cols))',
'if __name__ == "__main__":',
'    matrix=[[9,9,4],[6,6,8],[2,1,1]]',
'    tracemalloc.start(); t0=time.perf_counter()',
'    r=Solution_v1().longestIncreasingPath(matrix)',
'    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'    print(f"var1: lip={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0329_longest_increasing_path_in_a_matrix.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int R,C; vector<vector<int>>* G; vector<vector<int>> memo;',
'int dfs(int r,int c){ if(memo[r][c]) return memo[r][c]; int best=1; int dr[]={1,-1,0,0},dc[]={0,0,1,-1}; for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<R&&nc>=0&&nc<C&&(*G)[nr][nc]>(*G)[r][c]) best=max(best,1+dfs(nr,nc));} return memo[r][c]=best; }',
'int main(){',
'    vector<vector<int>> g={{9,9,4},{6,6,8},{2,1,1}}; G=&g; R=g.size();C=g[0].size(); memo.assign(R,vector<int>(C,0));',
'    auto t=chrono::high_resolution_clock::now();',
'    int ans=0; for(int r=0;r<R;r++)for(int c=0;c<C;c++) ans=max(ans,dfs(r,c));',
'    cout<<"var1: "<<ans<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 115. Distinct Subsequences
write(f"{BASE}/14_2d_dp/0115_distinct_subsequences.py", [
'"""LeetCode 115: Distinct Subsequences - Hard"""',
'import time, tracemalloc',
'# Variation 1: 2D DP',
'class Solution_v1:',
'    def numDistinct(self, s, t) -> int:',
'        m,n=len(s),len(t)',
'        dp=[[0]*(n+1) for _ in range(m+1)]',
'        for i in range(m+1): dp[i][0]=1',
'        for i in range(1,m+1):',
'            for j in range(1,n+1):',
'                dp[i][j]=dp[i-1][j]',
'                if s[i-1]==t[j-1]: dp[i][j]+=dp[i-1][j-1]',
'        return dp[m][n]',
'if __name__ == "__main__":',
'    tracemalloc.start(); t0=time.perf_counter()',
'    r=Solution_v1().numDistinct("rabbbit","rabbit")',
'    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'    print(f"var1: {r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0115_distinct_subsequences.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    string s="rabbbit",t="rabbit"; int m=s.size(),n=t.size();',
'    auto tv=chrono::high_resolution_clock::now();',
'    vector<vector<long long>> dp(m+1,vector<long long>(n+1,0));',
'    for(int i=0;i<=m;i++) dp[i][0]=1;',
'    for(int i=1;i<=m;i++) for(int j=1;j<=n;j++){dp[i][j]=dp[i-1][j];if(s[i-1]==t[j-1])dp[i][j]+=dp[i-1][j-1];}',
'    cout<<"var1: "<<dp[m][n]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-tv).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 72. Edit Distance
write(f"{BASE}/14_2d_dp/0072_edit_distance.py", [
'"""LeetCode 72: Edit Distance - Medium"""',
'import time, tracemalloc',
'# Variation 1: 2D DP',
'class Solution_v1:',
'    def minDistance(self, w1, w2) -> int:',
'        m,n=len(w1),len(w2)',
'        dp=[[0]*(n+1) for _ in range(m+1)]',
'        for i in range(m+1): dp[i][0]=i',
'        for j in range(n+1): dp[0][j]=j',
'        for i in range(1,m+1):',
'            for j in range(1,n+1):',
'                if w1[i-1]==w2[j-1]: dp[i][j]=dp[i-1][j-1]',
'                else: dp[i][j]=1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])',
'        return dp[m][n]',
'# Variation 2: 1D rolling',
'class Solution_v2:',
'    def minDistance(self, w1, w2) -> int:',
'        m,n=len(w1),len(w2)',
'        dp=list(range(n+1))',
'        for i in range(1,m+1):',
'            prev=dp[0]; dp[0]=i',
'            for j in range(1,n+1):',
'                temp=dp[j]',
'                if w1[i-1]==w2[j-1]: dp[j]=prev',
'                else: dp[j]=1+min(dp[j],dp[j-1],prev)',
'                prev=temp',
'        return dp[n]',
'if __name__ == "__main__":',
'    for Vi,Cls in enumerate([Solution_v1,Solution_v2],1):',
'        tracemalloc.start(); t0=time.perf_counter()',
'        r=Cls().minDistance("horse","ros")',
'        t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'        print(f"var{Vi}: dist={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
'# var2 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0072_edit_distance.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    string w1="horse",w2="ros"; int m=w1.size(),n=w2.size();',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<int> dp(n+1); iota(dp.begin(),dp.end(),0);',
'    for(int i=1;i<=m;i++){int prev=dp[0];dp[0]=i;for(int j=1;j<=n;j++){int tmp=dp[j];dp[j]=w1[i-1]==w2[j-1]?prev:1+min({dp[j],dp[j-1],prev});prev=tmp;}}',
'    cout<<"var1: "<<dp[n]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 312. Burst Balloons
write(f"{BASE}/14_2d_dp/0312_burst_balloons.py", [
'"""LeetCode 312: Burst Balloons - Hard"""',
'import time, tracemalloc',
'from typing import List',
'# Variation 1: Interval DP',
'class Solution_v1:',
'    def maxCoins(self, nums: List[int]) -> int:',
'        nums=[1]+nums+[1]; n=len(nums)',
'        dp=[[0]*n for _ in range(n)]',
'        for length in range(2,n):',
'            for l in range(0,n-length):',
'                r=l+length',
'                for k in range(l+1,r):',
'                    dp[l][r]=max(dp[l][r],nums[l]*nums[k]*nums[r]+dp[l][k]+dp[k][r])',
'        return dp[0][n-1]',
'if __name__ == "__main__":',
'    tracemalloc.start(); t0=time.perf_counter()',
'    r=Solution_v1().maxCoins([3,1,5,8])',
'    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'    print(f"var1: coins={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0312_burst_balloons.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    vector<int> n={1,3,1,5,8,1}; int sz=n.size();',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<vector<int>> dp(sz,vector<int>(sz,0));',
'    for(int len=2;len<sz;len++) for(int l=0;l<sz-len;l++){int r=l+len; for(int k=l+1;k<r;k++) dp[l][r]=max(dp[l][r],n[l]*n[k]*n[r]+dp[l][k]+dp[k][r]);}',
'    cout<<"var1: "<<dp[0][sz-1]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

# 10. Regular Expression Matching
write(f"{BASE}/14_2d_dp/0010_regular_expression_matching.py", [
'"""LeetCode 10: Regular Expression Matching - Hard"""',
'import time, tracemalloc',
'# Variation 1: 2D DP',
'class Solution_v1:',
'    def isMatch(self, s, p) -> bool:',
'        m,n=len(s),len(p)',
'        dp=[[False]*(n+1) for _ in range(m+1)]',
'        dp[0][0]=True',
'        for j in range(1,n+1):',
'            if p[j-1]=="*": dp[0][j]=dp[0][j-2]',
'        for i in range(1,m+1):',
'            for j in range(1,n+1):',
'                if p[j-1]=="*":',
'                    dp[i][j]=dp[i][j-2]  # use 0 times',
'                    if p[j-2]=="." or p[j-2]==s[i-1]:',
'                        dp[i][j]=dp[i][j] or dp[i-1][j]',
'                elif p[j-1]=="." or p[j-1]==s[i-1]:',
'                    dp[i][j]=dp[i-1][j-1]',
'        return dp[m][n]',
'if __name__ == "__main__":',
'    tracemalloc.start(); t0=time.perf_counter()',
'    r=Solution_v1().isMatch("aab","c*a*b")',
'    t1=time.perf_counter(); mem=tracemalloc.get_traced_memory()[1]; tracemalloc.stop()',
'    print(f"var1: match={r}, mem={mem}bytes, time={(t1-t0)*1e6:.2f}us")',
'# var1 mem = {} and time = {}',
])
write(f"{BASE}/14_2d_dp/0010_regular_expression_matching.cpp", [
'#include <bits/stdc++.h>',
'#include <chrono>',
'using namespace std;',
'int main(){',
'    string s="aab",p="c*a*b"; int m=s.size(),n=p.size();',
'    auto t=chrono::high_resolution_clock::now();',
'    vector<vector<bool>> dp(m+1,vector<bool>(n+1,false));',
'    dp[0][0]=true;',
'    for(int j=1;j<=n;j++) if(p[j-1]==\'*\') dp[0][j]=dp[0][j-2];',
'    for(int i=1;i<=m;i++) for(int j=1;j<=n;j++){',
'        if(p[j-1]==\'*\'){ dp[i][j]=dp[i][j-2]; if(p[j-2]==\'.\'||p[j-2]==s[i-1]) dp[i][j]=dp[i][j]||dp[i-1][j];',
'        }else if(p[j-1]==\'.\'||p[j-1]==s[i-1]) dp[i][j]=dp[i-1][j-1];',
'    }',
'    cout<<"var1: "<<dp[m][n]<<endl;',
'    auto e=chrono::high_resolution_clock::now();',
'    cout<<"var1 time="<<chrono::duration_cast<chrono::nanoseconds>(e-t).count()/1000.0<<"us"<<endl;',
'}',
'// var1 mem = {} and time = {}',
])

print("Section 14 2D DP done!")
